### ISSUE TITLE
GSAP Text Animations on Homepage

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#10]
**Objective** : I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

**Details**:
- Animate heading and subheading text on page load.
- Include subtle fade-in or slide-in animations for improved visual appeal.
- Ensure animations are responsive and do not affect performance on lower-end devices.
- Will add comments to code to ensure clarity for future contributors.

Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24.

Looking forward to your feedback!

**Comment by yashmandi** [comment]
thank you for raising the issue. i'll assign this issue after you complete the issue #11

**Comment by ishanguptaofficial** [comment]
Hello Scribbie-Notes Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by priyashuu** [comment]
Dear @yashmandi,

The work on issue #11 has been completed. As per our earlier discussion, could you please assign it to me? It would be great to have this in my task list as you promised.
