### ISSUE TITLE
Enhancements for User Engagement

### ISSUE THREAD

**Issue by Keerthi421** [Scribbie-Notes/notes-app#105]
Description

The application lacks personalized user engagement features, such as a greeting with the user's name upon sign-up, a daily motivational quote, current weather updates, attractive buttons for better user interaction, and moving background images. These enhancements could significantly improve user experience.
Steps to Reproduce

    Sign up or log in to the application.
    Observe the greeting displayed.
    Check for the absence of a motivational quote.
    Look for current weather information.
    Assess the design and functionality of the buttons.
    Review the background design for visual appeal.

Expected Behavior

Users should see a personalized greeting with their name, a random motivational quote, current weather, attractive buttons, and an engaging moving background.
Actual Behavior

Currently, users receive a generic greeting without personalization, quotes, or weather updates, the buttons lack visual appeal, and the background is static.
Screenshots

![image](https://github.com/user-attachments/assets/2f58a293-5108-4ef1-9b20-10cd5114cd15)

Additional Context

Integrating these features can improve user engagement and satisfaction. Consider using APIs for quotes and weather data, updating button designs for enhanced usability, and implementing CSS animations for moving backgrounds.
Please assign me this issue , I would like to work on this .

@yashmandi

**Comment by yashmandi** [comment]
i appreciate your suggestions @Keerthi421 , but currently focusing on other priorities right now. 
btw, i’m curious about your thoughts on background animations—could you share your ideas in detail what changes are u planning to make?

**Comment by Keerthi421** [comment]
@yashmandi , I had an idea of adding some of background images with quotes and with a scrolling option

**Comment by yashmandi** [comment]
sounds good to me, but im looking for background animations, can you think something related to that?

**Comment by Chandan-Kr-dev** [comment]
i can add  animations to the website scroll and load animations and buttons and else animations

**Comment by yashmandi** [comment]
> i can add animations to the website scroll and load animations and buttons and else animations

explain more please. i am just looking for scrolling animations, on scrolling it should go smoothly. and some bg animations.

**Comment by Chandan-Kr-dev** [comment]
i will add the animations like on hover animations , cards popping out or coming from the side one by one like a sequence of animations  and for bg animations i will add a animated background gif  or a video can be added related to the website

**Comment by yashmandi** [comment]
sounds good, but let's wait for @Keerthi421 's response.. what she is planning ;)

**Comment by Keerthi421** [comment]
@yashmandi , I am working on issue i have raised and I am not working on background animations
