### ISSUE TITLE
the user photo is not getting updated

### ISSUE THREAD

**Issue by AyushSharma72** [Scribbie-Notes/notes-app#108]
# Issue Template

## Description

when the user try to change the profile photo it do not get updated

## Steps to Reproduce
i will review the code and resolve the error in the backend or on the frontend

@yashmandi please assign this issue to me

**Comment by yashmandi** [comment]
thank you for raising this issue @AyushSharma72 , please explain me in detial what steps are you gonna take to resolve this issue, then we can assign this to you.

**Comment by AyushSharma72** [comment]
The user cannot change the profile photo I will 
1) check the code on frontend 
2) check the code on backend 
3) I will identify and resolve the issue.

**Comment by yashmandi** [comment]
thankyou for your detailed plan @AyushSharma72 

i just wanted to ask if you’re considering using any cloud services for the profile photo uploads. since i’ll be deploying this project soon, integrating with cloud services like AWS or GCP would be essential for handling user photos in the deployed version. if that's part of your approach, i understand, but we’re currently not looking to integrate those solutions just yet.

i truly value your approach... waiting for your response ;)

**Comment by AyushSharma72** [comment]
Aren't you using mongodb cluster already??
The photo is saved somewhere right ??
I just want to resolve the error of why the photo is not saved 
If you use AWS without resolving the error how it will work ??

**Comment by ishanguptaofficial** [comment]
Hello Scribbie-Notes Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by yashmandi** [comment]
you can work on it @AyushSharma72 let's see what you have 😊

**Comment by AyushSharma72** [comment]
> you can work on it @AyushSharma72 let's see what you have 😊

Ok thanks

**Comment by AyushSharma72** [comment]
> you can work on it @AyushSharma72 let's see what you have 😊

there is error in login and sign up i will start working when these issues are merged 
i can work on those issues as well but you already assigned them to someone issue number #119

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by AyushSharma72** [comment]
> any update @AyushSharma72 ?

I will do it by today

**Comment by AyushSharma72** [comment]
> any update @AyushSharma72 ?

GOOGLE_API_TOKEN="" can u give me this value ??
