### ISSUE TITLE
Update Testimonial Section

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#11]
**Objective**: I propose replacing or enhancing the current testimonial section by something like this . 

https://github.com/user-attachments/assets/cc24279f-4a56-4938-987b-0d5eff596ecc

**Comment by yashmandi** [comment]
issue #11 assigned to @priyashuu 
thank you for raising this issue!

**Comment by Prithvi2004** [comment]
Hey @yashmandi i have more experience in web development could you please assign me this issue

**Comment by yashmandi** [comment]
> Hey @yashmandi i have more experience in web development could you please assign me this issue

issues are assigned on first come first serve basis, i'd request you to find other issues @Prithvi2004

**Comment by priyashuu** [comment]
![Uploading Screenshot 2024-10-07 172658.png…]()

**Comment by priyashuu** [comment]
![Screenshot 2024-10-07 172658](https://github.com/user-attachments/assets/05d53e0c-6f0c-4821-8f91-ef626c082323)
