### ISSUE TITLE
Bug: The adding note svg is not aligned to the center. 

### ISSUE THREAD

**Issue by userAdityaa** [Scribbie-Notes/notes-app#114]
# Issue Template

## Description
The adding note svg when the user has not added anything is not aligned to the center of the website. 

## Expected Behavior
- The Svg should be center aligned.
Describe what you expected to happen.

## Actual Behavior
- The Svg is mostly on the left of the screen.

Describe what actually happens when you follow the steps.

## Screenshots
<img width="1440" alt="Screenshot 2024-10-06 at 6 45 58 AM" src="https://github.com/user-attachments/assets/52d4649a-3e3b-4429-9161-096b0ed143e4">

**Comment by userAdityaa** [comment]
Hey @theashikagupta, Assign this issue to me with the label gssoc.

**Comment by yashmandi** [comment]
@userAdityaa this issue has been resolved previously, try to run 'git pull' on your terminal, you'll get the latest updates of the repo. thankyou!
![image](https://github.com/user-attachments/assets/c27066f6-541f-44bb-a108-f2ae31305052)
