### ISSUE TITLE
want to implement user authentication and Reminders and due dates

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [Scribbie-Notes/notes-app#115]
# Issue Template

## Description
I want to implement user authentication and Remainder and due dates because these features are missing in this application.
## Steps to Reproduce
Version: 1.0.0
Environment: Development
Conditions: Observed on Google Chrome (Version 118.0.5993.90) on macOS.

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'login page (login.html)' and enter credentials.
2. Click on 'login submit' (do not have a account--sign up it opens sign up page then enter credentials and click on sign up button) 
3. Scroll down to 'validates the login and sign up pages and give pop up messages'
5. create a reminder and due date section 
6. enter the details and  create reminder 
7. error message--Failed to create a reminder

## Expected Behavior
successful login and sign up 
reminder along with the date is save --success message

## Actual Behavior

authentication failed
failed to create a reminder

## Screenshots

![20241006_092945](https://github.com/user-attachments/assets/51ff9bf6-a036-4c14-b061-728159cccda9)
![20241006_092959](https://github.com/user-attachments/assets/70c551cf-b383-4e2f-9a0e-224e926aed78)

## Additional Context

boost the security of the application

**Comment by yashmandi** [comment]
incorrect project issue raised, hence closing
