### ISSUE TITLE
Dark Mode Not Applying Styles Correctly

### ISSUE THREAD

**Issue by RaiDevX8** [Scribbie-Notes/notes-app#117]
# Issue Template

# Issue Template

## Description

Dark mode is not applying the expected styles on the note-taking website. This issue occurs in the latest version of the application when viewed in a modern browser.

## Steps to Reproduce

1. Go to the  website.
2. Settings
3. Toggle the dark mode switch.
4. Observe that the styles for dark mode are not applied correctly.

## Expected Behavior

The dark mode should change the theme colors appropriately.

## Actual Behavior

The dark mode toggle does not apply the correct styles, and the site remains in light mode.

## Screenshots

![Dark mode not working](
![Screenshot 2024-10-06 173657](https://github.com/user-attachments/assets/7ccd4a92-f1cd-4abe-bacb-2c0021f6edc0)
)

## Additional Context

This issue was observed in the latest version of the application on Chrome. Console logs indicate that the dark mode styles are not being applied.

**Comment by HarshithaSivalingala** [comment]
The following is my approach.
Ensure dark mode styles are correctly defined and not overridden, verify the toggle applies the right class or attribute, inspect elements and applied styles using Chrome DevTools, check JavaScript for errors in theme switching or localStorage persistence, clear cache to reload fresh styles, and test across different browsers to identify if it's a browser-specific issue.
I want to work on this. Could you please assign it to me @yashmandi ?

**Comment by RaiDevX8** [comment]
@yashmandi i was the one who found the issue and approached to solve it

**Comment by STSonyThomas** [comment]
Hey can I work on this since it seems like there has been no progress on this issue for the last few days

**Comment by yashmandi** [comment]
any update @RaiDevX8

**Comment by RaiDevX8** [comment]
> any update @RaiDevX8 

I did this part in last PR but she closed it I don't get why she closed the PR
