### ISSUE TITLE
Welcome Text Misalignment on Sign-Up Page

### ISSUE THREAD

**Issue by RaiDevX8** [Scribbie-Notes/notes-app#118]
# Issue Template
## Description

The welcome text on the sign-up page is not aligned properly to the center, affecting the overall appearance of the page.

## Steps to Reproduce

1. Go to the sign-up page of the note-taking website.
2. Observe the welcome text displayed.

## Expected Behavior

The welcome text should be centered in the view.

## Actual Behavior

The welcome text is misaligned and appears off-center.

## Screenshots

![Welcome text alignment issue](
![Screenshot 2024-10-06 172452](https://github.com/user-attachments/assets/8e1e876a-0cdb-4766-b715-6812dc14b538)
)

## Additional Context

This issue affects the user experience on the sign-up page and should be addressed for a more polished look.

**Comment by yashmandi** [comment]
the 'welcome to scribbie' is put intentionally on the left side, not by mistake. so no need to fix it ;)
