### ISSUE TITLE
enhance the website

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#12]
**Objective**: I propose replacing or enhancing this page 
![Screenshot 2024-10-02 002705](https://github.com/user-attachments/assets/e2168690-2a1c-4382-a1b1-50ff76ec4dce)
to this

https://github.com/user-attachments/assets/60846d7f-e939-44d0-a429-d1b92f7a78fd

Please assign this issue to me as I’d like to implement this change. I am also a contributor in GGSOCExt 24.

Looking forward to your feedback!

**Comment by yashmandi** [comment]
thank you for raising the issue. i'll assign this issue after you complete the issue #11
