### ISSUE TITLE
{BUG} issue in Contact Us we can create a different page for that

### ISSUE THREAD

**Issue by Aditya-edith** [Scribbie-Notes/notes-app#124]
We can add one more page for contact us such that if a user is unsatisfied or even want to contact us they can easily send us a mail using that section .

As whatever we are doing is for user so that is the most important thing to connect

![scribbie1](https://github.com/user-attachments/assets/8235971f-1e8f-4c1b-a914-183c4701502d)

**Comment by yashmandi** [comment]
we appreciate the thought @Aditya-edith , but right now we’re focusing on other features. we’ll definitely consider it for the future ;)
