### ISSUE TITLE
[ feature] add one option in note section to download as a PDF

### ISSUE THREAD

**Issue by Aditya-edith** [Scribbie-Notes/notes-app#126]
We can add one feature that includes download as  PDF file so that user can add notes as well as download if they want to store it anywhere and print as well.

we can add a download button 
onClick the download we will just make a file and download it using an API
Extracts the content from the request body.
Checks if content is provided, returning an error if it's missing.
Creates a new PDF document using PDFKit.
Sets the appropriate headers for PDF download.
Pipes the PDF directly to the response.
Adds the content to the PDF.
Finalizes the PDF, which sends it to the client.

![image](https://github.com/user-attachments/assets/0ac9c4aa-4279-4d40-9f19-07a423bf11f6)
in this image here at bottom or anywhere in that section

**Comment by yashmandi** [comment]
i really appreciate your issue @Aditya-edith , but currently we're not looking for such feature in Scribbie, ;)
