### ISSUE TITLE
Adding Tag Symbols, Star/Favorite, Priority Flag, and Checkbox Features

### ISSUE THREAD

**Issue by Keerthi421** [Scribbie-Notes/notes-app#127]
Description

Currently, Scribbie doesn’t offer the ability to organize or prioritize notes efficiently. Adding these features would significantly improve usability:
Tags: Let users add tags like personal, work, or study to categorize their notes.

Star/Favorite: Allow users to star important notes for easy access.

Priority Flag: Introduce color-coded flags for prioritizing notes (e.g., red for high priority).
    
Checkbox: Provide a checkbox feature within notes for task tracking and marking items as complete.

Color-Coding: Introduce color options based on task type (e.g., blue for school, green for activity) for better visual organization.

Steps to Reproduce:

    (1)Go to the dashboard after logging in.

  (2)Try creating or editing a note.
  
   (3)See that you can’t add tags, stars, flags, or checkboxes.

Expected Behavior:

I’d expect users to easily categorize notes, mark important ones for quick access, set priority levels using flags, and track tasks with checkboxes.
Actual Behavior

None of these features are currently available, making it harder to manage and prioritize notes effectively.
Screenshots

![image](https://github.com/user-attachments/assets/9d46b32f-f311-47da-81a9-25ee722c719c)

Additional Context

These features would enhance note organization and make the platform more user-friendly, especially for users with multiple notes across various categories.
Please do assign me this issue . I will work on this .
@yashmandi

**Comment by yashmandi** [comment]
u can work on it @Keerthi421 , remember to take the latest pull from repo

**Comment by Keerthi421** [comment]
ok @yashmandi

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..
