### ISSUE TITLE
[BUG]:  Feedback link in the footer doesn't redirect to the feedback form

### ISSUE THREAD

**Issue by HarshadaGirase** [Scribbie-Notes/notes-app#128]
Description
The "Feedback" link in the footer of the website is currently non-functional. When clicking the link, no action is triggered, and the feedback form does not appear as expected. 

Steps to Reproduce
Please provide step-by-step instructions on how to reproduce the issue:

Go to the website's homepage or any other page.
Scroll down to the footer section.
Click on the "Feedback" link.
Observe that no action or redirect occurs.

Expected Behavior
When the "Feedback" link in the footer is clicked, it should either:

Redirect the user to the feedback form page.
Open a modal or overlay that allows the user to submit feedback.
Actual Behavior
When the "Feedback" link is clicked, no action is triggered, and the user remains on the same page with no feedback form or modal appearing.

![Screenshot (348)](https://github.com/user-attachments/assets/cd10b381-82f5-4c5c-9378-aa8d842dc344)

**Comment by zaheer-Khan3260** [comment]
Can i work on this problem?

**Comment by yashmandi** [comment]
it has been already assigned , find another issue to contribute ;)

**Comment by Saurabhchaudhary9799** [comment]
hey @yashmandi ,  If there is no active PR on this issue till now , so can i work on this issue.

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
