### ISSUE TITLE
Voice Commands Implementation 

### ISSUE THREAD

**Issue by AasthaSingh28** [Scribbie-Notes/notes-app#129]
## Description

Implement voice commands to create notes.
This can be particularly useful for users who prefer a hands-free experience or have mobility limitations.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'create new note'
2. Click on 'Add new audio note.'

## Expected Behavior

User can record their note in voice formal. 
@yashmandi - Kindly assign me the issue I want to work on this

**Comment by yashmandi** [comment]
thank you for your interest @AasthaSingh28 , but this issue has already been raised, and someone else is currently working on it.
you can check the existing issue here: #6
