### ISSUE TITLE
Add "Forgot Password" Feature to Login Page

### ISSUE THREAD

**Issue by Mdraza78** [Scribbie-Notes/notes-app#13]
Implement a "Forgot Password" link on the login page. This link should direct users to a password recovery process, where they can enter their registered email address to receive instructions for resetting their password. This enhancement will improve user accessibility and overall experience.

**Comment by shubham-mehta-002** [comment]
Kindly assign this issue to me

**Comment by OINDIL** [comment]
Hey maintainers, I would love to work on this feature which is "forgot-password implementation in login page". I have forked the repo just to check the code structure and I have found out the .env files are there with the fork. There are credentials also. I don't think this should be like this. If so please let me know.
![Screenshot from 2024-10-02 12-18-07](https://github.com/user-attachments/assets/888de642-b591-4056-9548-998895fa738c)

**Comment by yashmandi** [comment]
thank you @Mdraza78 for raising the issue. you can work on this issue ;)

**Comment by theashikagupta** [comment]
@Mdraza78 How much time it will take ?

**Comment by itznayan** [comment]
@theashikagupta @yashmandi Please assign this issue to me.

**Comment by SatyamTiwari069** [comment]
please assign me the task as for gssoc24 extd

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by theashikagupta** [comment]
Assigned @SatyamTiwari069

**Comment by SatyamTiwari069** [comment]
hey i have completed the isssue .. but it is not getting pushed...even i am not able to create a PR.. Please guide me so that i can push my work to you....

**Comment by SatyamTiwari069** [comment]
Major changes i did were


Backend Implementation
API Route for Requesting Password Reset:

Create an API route that accepts the user's email or username.
This route should verify the email/username, generate a password reset token, and send a password reset email to the user.
Example route:

js
Copy code
// Express.js route
app.post('/forgot-password', async (req, res) => {
    const { email } = req.body;
    const user = await User.findOne({ email });
    if (!user) {
        return res.status(400).send('User not found');
    }
    // Generate reset token
    const resetToken = generateResetToken();
    user.resetToken = resetToken;
    await user.save();

    // Send reset email
    sendPasswordResetEmail(user.email, resetToken);
    res.send('Password reset link sent to your email');
});
Token Generation:

You can use a library like crypto to generate a random token for password reset.
Example:

js
Copy code
const crypto = require('crypto');
function generateResetToken() {
    return crypto.randomBytes(20).toString('hex');
}
Send Reset Email:

Use a mailing service like Nodemailer to send an email containing a reset link with the token.
Example:

js
Copy code
const nodemailer = require('nodemailer');

function sendPasswordResetEmail(email, token) {
    const resetLink = `https://yourapp.com/reset-password?token=${token}`;
    const mailOptions = {
        from: 'yourapp@example.com',
        to: email,
        subject: 'Password Reset',
        text: `Click the link to reset your password: ${resetLink}`
    };
    // Send email using nodemailer
}
API Route to Reset the Password:

Create a route to handle the password reset once the user clicks the link in the email.
Example:

js
Copy code
app.post('/reset-password', async (req, res) => {
    const { token, newPassword } = req.body;
    const user = await User.findOne({ resetToken: token });
    if (!user) {
        return res.status(400).send('Invalid token');
    }
    user.password = newPassword;  // Hash this password before saving
    user.resetToken = undefined;  // Clear the reset token
    await user.save();
    res.send('Password updated successfully');
});
Frontend Implementation
Forgot Password Form:

Add a "Forgot Password?" link to your login page.
When clicked, this should navigate to a form where users enter their email.
Example:

jsx
Copy code
// React.js form
function ForgotPassword() {
    const [email, setEmail] = useState('');
    const handleSubmit = async (e) => {
        e.preventDefault();
        await fetch('/forgot-password', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email })
        });
    };
    return (
        <form onSubmit={handleSubmit}>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Enter your email" required />
            <button type="submit">Submit</button>
        </form>
    );
}
Reset Password Form:

Add a form that accepts the new password when the user clicks the password reset link.
Example:

jsx
Copy code
function ResetPassword() {
    const [password, setPassword] = useState('');
    const [token, setToken] = useState(new URLSearchParams(window.location.search).get('token'));

    const handleSubmit = async (e) => {
        e.preventDefault();
        await fetch('/reset-password', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ token, newPassword: password })
        });
    };

    return (
        <form onSubmit={handleSubmit}>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter new password" required />
            <button type="submit">Reset Password</button>
        </form>
    );
}
Security Considerations
Token Expiry: Set an expiration time for the password reset token (e.g., 1 hour).
Password Hashing: Always hash passwords before saving them to the database.
Email Confirmation: Send confirmation after the password has been successfully reset.

**Comment by theashikagupta** [comment]
@SatyamTiwari069 What's the error ? Attach screen shot for clarity.

**Comment by theashikagupta** [comment]
Assigned @Sourabh782
