### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Scribbie-Notes/notes-app#134]
Dear Project Admin, [notes-app](https://github.com/Scribbie-Notes/notes-app)

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by aditya-bhaumik** [comment]
@yashmandi please make sure to follow these guidelines

**Comment by yashmandi** [comment]
sure @aditya-bhaumik @AKSHITHA-CHILUKA , we'll take care of those things ;)

**Comment by AKSHITHA-CHILUKA** [comment]
@yashmandi all your closed issue's and pr should also have labels please add them

**Comment by AKSHITHA-CHILUKA** [comment]
![image](https://github.com/user-attachments/assets/6bf7097c-3597-4cc0-be6a-a9f6b10c938f)
see no labels , all your contributors are not getting points bcz of this

**Comment by theashikagupta** [comment]
@AKSHITHA-CHILUKA  Ma'am kindly we didn't add labels on these issues before closing because these are not assigned to anyone because of duplicate issue .Others PR's and issues have correct labelling from starting .
