### ISSUE TITLE
[Bug] : Contact Us page is not working 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Scribbie-Notes/notes-app#139]
# Issue Template

## Description
 I want to design working Contact us page for you from backend to frontend everything with work finely.

## Steps to Reproduce
go to contact us page 

## Screenshots
![contact us](https://github.com/user-attachments/assets/1b72da2c-85ef-455e-9238-6a379103a04b)

i can create this type of contact us page with you get user response from contact form.
## Additional Context
I want your email id for sending you the contact us messages.
assigned this issue under gssoc 24 and hactoberfest.

**Comment by yashmandi** [comment]
thank you for raising this issue @VinayLodhi1712  , but we're not planning to create a seperate page for contact us, as we've decided to add the contact section in about us section itself.
