### ISSUE TITLE
Add Color Palette to Enhance Website UI/UX

### ISSUE THREAD

**Issue by Mehtarishita** [Scribbie-Notes/notes-app#14]
I would like to propose adding a color palette to improve the website's UI and UX. Currently, the website design lacks a cohesive and visually appealing color scheme, which can impact overall readability and user engagement. 
![image](https://github.com/user-attachments/assets/bc4fd50b-844e-4aa9-ba61-d603e0475051)
Over here as well and in the whole website.
Please let me know if there are any specific color preferences or guidelines that need to be followed. I am happy to start working on this and create a mockup for the proposed changes.

**Comment by yashmandi** [comment]
thank you @Mehtarishita for raising the issue. we're maintaining the current color theme for entire site for now, and not planning any other color themes.
