### ISSUE TITLE
Your website scroll bar is not looking good and not suiting on your website

### ISSUE THREAD

**Issue by VinayLodhi1712** [Scribbie-Notes/notes-app#140]
# Issue Template

## Description
the default scroll bar is not suited on your website

## Steps to Reproduce
go to home page and scroll

## Screenshots
![notscrollbar](https://github.com/user-attachments/assets/f9991a96-ba32-40e6-a4e4-7d5db4c503fd)

https://github.com/user-attachments/assets/07122046-afc6-434d-a273-3dd288ad790e

## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
you can work on this @VinayLodhi1712 , try to maintain the website theme
