### ISSUE TITLE
Backend: login endpoint is giving 400 (Bad request ) error

### ISSUE THREAD

**Issue by Abhishek332** [Scribbie-Notes/notes-app#141]
# Issue Template

## Description
When hitting the login api with correct payload which contains email and password giving 400 error.

**Comment by theashikagupta** [comment]
Assigned ! You can work on it

**Comment by Abhishek332** [comment]
Thankyou @theashikagupta.
I fixed this issue. Could you please review and merge it with label `hacktoberfest`.

https://github.com/user-attachments/assets/c88717b4-6fe4-42ce-9b71-5b38ed14b512
