### ISSUE TITLE
updated the pricing page 

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#143]
# Issue Template

## Description
@yashmandi , could you please reopen issue #12 ? I’ve been reconsidering the color palette, and I believe I can choose one that will better suit the website’s overall design. If you're open to it, I would be happy to work on this issue. Of course, if you want that for your website, I would also appreciate any additional input or feedback from your side to ensure it aligns with your vision. Thank you

**Comment by yashmandi** [comment]
okay, you can work on it, i've reopened it ;)
