### ISSUE TITLE
Feature : Enhancing UI of What our customers think section 

### ISSUE THREAD

**Issue by VinayLodhi1712** [Scribbie-Notes/notes-app#145]
# Issue Template

## Description

Your What our customers think section is not looking good UI.
I wanted to create its UI using Card Component and swiper.js  Like from this -
![customrthink](https://github.com/user-attachments/assets/f9ba9569-6f9f-4e5b-98e3-03a07ca320b9)

to this -
![review](https://github.com/user-attachments/assets/aaa2d7f2-626f-4cd8-b49b-ced642421c1b)

I will mainain your website background them and content with font-styles.
assign issue under gssoc and hactoberfest.

**Comment by yashmandi** [comment]
thanks for your interest @VinayLodhi1712 , but the current one is enhanced one with one of the contributors. so there's no plan of re-enhancing it. sorry about that.
