### ISSUE TITLE
Backend: /get-all-notes endpoint is giving 500 internal server error

### ISSUE THREAD

**Issue by Abhishek332** [Scribbie-Notes/notes-app#151]
# Issue Template

## Description

Backend: /get-all-notes endpoint is giving 500 internal server error

## Steps to Reproduce
1. Login
2. Inspect and go to network tab

## Expected Behavior
should fetch all notes without error

## Screenshots
<img width="1440" alt="Screenshot 2024-10-10 at 12 18 45 AM" src="https://github.com/user-attachments/assets/382b00dc-9468-4339-baf9-92ce62570e4c">

**Comment by harshbhar0629** [comment]
Can i work on this issue???

**Comment by Abhishek332** [comment]
@yashmandi Sorry, I was stuck in some release deadlines. I just take the pull of main. 
This issue is fixed by someone, we can close this issue as also
