### ISSUE TITLE
adding navbar

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#152]
# Issue Template

## Description
Objective: I propose enhancing the navbar like this

https://github.com/user-attachments/assets/b77b0b3c-563d-4515-b404-261c52a043de

Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback

**Comment by yashmandi** [comment]
go ahead, if we like it, we'll merge it
