### ISSUE TITLE
add dark mode toggle button

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#153]
# Issue: Add Dark Mode Toggle Button

## Description

A dark mode toggle button is needed for the application to allow users to switch between light and dark modes. This feature should be available on all pages and remember the user's preference. It should also smoothly integrate with the existing design and components.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to any page of the website.
2. Look for a dark mode toggle button.
3. Click on it to attempt switching modes.
4. Observe if there is a toggle functionality or if the feature is missing.

## Expected Behavior

A visible dark mode toggle button should allow users to seamlessly switch between light and dark themes. The theme preference should be stored in local storage or a similar method to persist across sessions.

## Actual Behavior

Currently, there is no option to toggle between light and dark modes.

## Additional Context

The dark mode should be implemented with smooth transitions for colors and themes. Consider accessibility aspects such as contrast ratios when designing the dark theme.

**Comment by Asjdnnc** [comment]
i can add this feature in the website 
please assign me this task

**Comment by theashikagupta** [comment]
@priyashuu Do you want to work on this ?

**Comment by theashikagupta** [comment]
Assigned @priyashuu

**Comment by priyashuu** [comment]
mam please @theashikagupta  #155 I’ve incorporated libraries like GSAP and Framer Motion to enhance the animations. If there are any specific elements you’d like to see in the navbar or if there’s something that doesn’t meet your expectations, I’d be happy to make the necessary changes. "Please add a Level 3 feature to the Navbar as it was assigned in the issue creation. . What else do you want in the backend,please dont do this

**Comment by priyashuu** [comment]
@yashmandi

**Comment by theashikagupta** [comment]
Okay fine !

**Comment by priyashuu** [comment]
thank you so much @theashikagupta 🫡

**Comment by AADESHak007** [comment]
Hey @theashikagupta I would Like to work on this issue
