### ISSUE TITLE
Add Contact Page

### ISSUE THREAD

**Issue by priyashuu** [Scribbie-Notes/notes-app#154]
# Issue: Add Contact Page

## Description

A Contact page needs to be added to the website. This page should include sections for user inquiries, social media links, and any relevant contact information. It should be designed to fit within the existing style and structure of the website. The page should be fully responsive.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to the website’s homepage.
2. Search for a link or section for contacting the team.
3. Notice that a Contact page is currently missing.
4. No contact information is available directly on the site.

## Expected Behavior

- A Contact page should be present with a form where users can enter their name, email, and message.
- The page should include links to the organization’s social media handles.
- It should be easy to find from the navbar or footer.

## Actual Behavior

There is no Contact page or easy way to find contact details on the website.

## Additional Context

The Contact page could also integrate with a backend service for form submissions or display a map for physical office locations. Consider adding validations for the contact form fields.

**Comment by yashmandi** [comment]
we're planning to add the 'contact us' section in the 'about us' section itself, so as of now, not planning to create a different page for it.
