### ISSUE TITLE
[FEATURE]: Add an FAQ Section with Accordion Functionality to Website

### ISSUE THREAD

**Issue by Someshog** [Scribbie-Notes/notes-app#157]
## Description

I would like to propose the addition of a Frequently Asked Questions (FAQ) section on our website. This feature aims to enhance user experience by providing quick access to common queries and reducing the volume of support requests.

## Steps to Reproduce

No FAQ section is present at the bottom of the website.

## Expected Behavior

Users should be able to easily find answers to their questions in a dedicated FAQ section, leading to improved satisfaction and reduced support inquiries.

## Actual Behavior

Currently, users may struggle to find information, leading to frustration and increased support requests.

## Screenshots

N/A (as this is a request for a new feature)

## Additional Context
Adding an FAQ section can also improve our site's SEO, potentially attracting more visitors. Regularly updating the section will keep it relevant and helpful for users.

**Comment by theashikagupta** [comment]
Assigned @Someshog
