### ISSUE TITLE
Feature Request: Basic Text Editor

### ISSUE THREAD

**Issue by theashikagupta** [Scribbie-Notes/notes-app#160]
Feature Description: We need to implement a basic text editor within the application that will allow users to create and edit notes with basic formatting options. This is a fundamental feature for the notes-taking app and should be simple, intuitive, and responsive.

Key Functionalities:

Add Text Formatting Options while creating or editing note.

Bold (Ctrl + B)
Italic (Ctrl + I)
Underline (Ctrl + U)
Headings (H1, H2, H3)
Bulleted Lists and Numbered Lists.
Text alignment options (left, center, right).

**Comment by ManasaNagaram** [comment]
Can i work on this?

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
