### ISSUE TITLE
Modification of README.md file & Creation of LICENSE File for project

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [Scribbie-Notes/notes-app#161]
# Issue Template

### 1) Add animated line separators and add GSSoC 2024 Extended accepted banner
I want to add animated line separators in the README.md file to make it look more attractive and readable. I would also like to add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.

### 2) Add a **Team section**
Add a Team Section for the Contributors to know who to refer to when they need help about the project.

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors. I would like to update it and try to **automate** the process.

## 2. Addition of a LICENSE File to the project
The presence of a LICENSE file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a LICENSE file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.

### 1) Add animated line separators and add GSSoC 2024 Extended accepted banner
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Add a **Team section**
![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/0969639b-8d08-4c37-86a4-e5bcf91f0e99)

I want to update it and try to automate it to mention all the current contributors:
![image](https://github.com/user-attachments/assets/cd80b8a0-1d24-48ea-a448-1e77210f537a)

## 2. Addition of a LICENSE File to the project
MIT LICENSE Reference:
![image](https://github.com/user-attachments/assets/c86b485a-b0c7-4717-8b0b-1a24191a3675)

## Additional Context

I would like to work on the issues in order to make this repository more scalable and readable for the contributors and other users. Please assign this issue to me under **level3** so that I can work on it.

**Comment by yashmandi** [comment]
thank you for your suggestions! however, these changes aren't currently required for the project. we appreciate your understanding!
