### ISSUE TITLE
[BUG] 🐞 Validation Checks in all forms

### ISSUE THREAD

**Issue by Akshithsaai** [Scribbie-Notes/notes-app#164]
## Description

I want ensure proper Validation in every form / Input user enter so that data will not create any problems ahead. 

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

### Example
1. Go to Signup
2. Click on Name
3. Enter a number 
4. ( Name cant be a number type ryt, Yet itworks!!) I have created an account with that.

## Expected Behavior

I expect it to check every form/ input data even after signup also . 

## Actual Behavior

Describe what actually happens when you follow the steps.
Data Should be Relatable to the label . 
Number , email, phone number , password fields should be validated correctly.

## Screenshots
![image](https://github.com/user-attachments/assets/052cf9ad-ae79-4052-8649-bf3e0951b277)

## Additional Context

I would Like to work on any additonal Issue also. 
Btw I loved the UI . Very Neat and simple. I want to contribute it to be the best..

**Comment by harshbhar0629** [comment]
Can i work on this issue??

**Comment by Rugved7** [comment]
Can you please allo me to work on this issue ?

**Comment by yashmandi** [comment]
> Can you please allow me to work on this issue ?

@Akshithsaai  is already working on this

**Comment by theashikagupta** [comment]
Assigned @harshbhar0629
