### ISSUE TITLE
feat : Add Multi-Select Functionality for Notes

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#167]
# Issue Template

## Description
This feature request proposes adding multi-select functionality for notes within the application. The ability to select multiple notes simultaneously will enhance the user experience, enabling users to perform bulk actions such as deleting, archiving, or pinning notes more efficiently.

### Key Features
**Multi-Select Mode**: Allow users to select multiple notes by enabling a selection mode.
**Bulk Actions**: Perform actions (e.g., delete, archive, move) on all selected notes at once.

## Screenshots
[Screencast from 2024-10-12 09-32-07.webm](https://github.com/user-attachments/assets/05ec2a1a-0671-4c38-a531-089404468fca)

## Expected Outcome
Upon implementation, users will be able to:
- Select multiple notes using the multi-select mode.
- Apply bulk actions to selected notes.

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Thanks for raising this issue . I appreciate your work this feature is really useful . Go ahead !! @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
> Thanks for raising this issue . I appreciate your work this feature is really useful . Go ahead !! @Saurabhchaudhary9799

Thanks @theashikagupta

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by Saurabhchaudhary9799** [comment]
Hey @theashikagupta , I also want to create two new issues regarding deleting and pinned multiple notes , can you assign me for both issues if I create

**Comment by theashikagupta** [comment]
Multiple selection functionality is already done in this PR then why again ? @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
This PR is only for adding background on multiple notes together. I want to make separate issue for these features
