### ISSUE TITLE
[FEATURE] : Adding a confirmation check  before Logging Out .

### ISSUE THREAD

**Issue by DevanshS9881** [Scribbie-Notes/notes-app#169]
## Description

Currently, there is no confirmation dialog when users click the "Log Out" button. This can lead to accidental logouts, causing potential loss of unsaved notes.  I propose to implement a confirmation dialog that prompts users to confirm their intention to log out which will ultimately enhance the user experience.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to Home Page of the website.
2. Click on Profile Icon.
3. Select the Log Out option
4. Observe that the user is logged out without any confirmation prompt.

## Expected Behavior

When clicking the "Log Out" button, a confirmation dialog should appear, asking the user to confirm their decision to log out.

## Actual Behavior

Clicking the "Log Out" button immediately logs the user out without any warning or confirmation.

**Comment by DevanshS9881** [comment]
Hello !! I would like to work on this issue and as such can you please assign it to me under GSSoC extd and hactoberfest accepted label

**Comment by theashikagupta** [comment]
Assigned @DevanshS9881

**Comment by Sourabh782** [comment]
hello i see this issue idle for about a week, if this issue is free, can i contribute to it? :))

**Comment by theashikagupta** [comment]
Assigned @Sourabh782

**Comment by Sourabh782** [comment]
> Assigned @Sourabh782

Thanks working on it 👍👍
