### ISSUE TITLE
Bug: Fix the icon bug in password 

### ISSUE THREAD

**Issue by theashikagupta** [Scribbie-Notes/notes-app#17]
![Screenshot 2024-10-02 132618](https://github.com/user-attachments/assets/27c91ab3-8704-411e-87e9-f9f6c5a3752d)
![Screenshot 2024-10-02 132626](https://github.com/user-attachments/assets/e56129e0-0db7-4e10-826f-0080ddbdab40)

Reverse these icons

**Comment by ManojithBhat** [comment]
can you please assign this to me ? I can work on this.

**Comment by theashikagupta** [comment]
Assigned to you @ManojithBhat !
