### ISSUE TITLE
bug :  Header is not displaying in some routes

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#170]
## Description
when i clicking on some header links like testimonial, pricing and contact us , the header is not displaying in these pages 

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'Homepage' 
2. Click on 'Testimonial or Pricing or Contact Us'
3. See error

## Expected Behavior
when i redirect to these pages after clicking header links , header should be visible

## Actual Behavior
when i clicking on some header links like testimonial, pricing and contact us , the header is not displaying in these pages 

## Screenshots
[Screencast from 2024-10-12 14-11-41.webm](https://github.com/user-attachments/assets/0755d3b1-e8fd-4798-a004-59ba9803aca5)

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
