### ISSUE TITLE
[ENHANCEMENT] Integration of TinyMCE

### ISSUE THREAD

**Issue by KGupta2601** [Scribbie-Notes/notes-app#176]
## Description

The aim to integrate TinyMCE into the Scribbie Notes App to enhance the existing text editing capabilities. This integration will provide a more robust and feature-rich text editor compared to the current basic implementation. TinyMCE offers advanced formatting options, an intuitive user interface, and a plugin ecosystem that allows for extensive customization.

## Steps to Reproduce

1. Review the current text editing capabilities in the Scribbie Notes App.
2. Identify the limitations of the existing basic text editor.
3. Compare with TinyMCE's features and functionalities, including:
   - Advanced formatting options (custom font styles, text color, background color, etc.)
   - WYSIWYG interface for real-time formatting
   - Customizable toolbar
   - Plugin support for additional functionalities

## Expected Behavior

The integration of TinyMCE should result in a significantly improved text editing experience, allowing users to create and edit notes with a wide range of formatting options and an intuitive interface.

@theashikagupta Kindly assign me this issue along with the labels of gssoc extended,hacktoberfest and level

**Comment by KGupta2601** [comment]
@yashmandi Kindly assign me this issue along with the labels of gssoc extended,hacktoberfest and level

**Comment by theashikagupta** [comment]
Thanks for raising this issue .You can work on this. @KGupta2601
