### ISSUE TITLE
[FEATURE] : Dynamic Search Results Update in Search Bar on homepage

### ISSUE THREAD

**Issue by DevanshS9881** [Scribbie-Notes/notes-app#177]
# Issue Template

## Description

The search bar on the homepage of the website does not filter results until the search button is clicked. I propose that the search results should be updated dynamically as the user types, allowing for a more efficient and user-friendly experience.

## Steps to Reproduce
 1. Go to the homepage of the website.
 2. Locate the search bar.
3 .Start typing in the search bar.
4. Notice that the results do not filter until the search button is clicked.

## Expected Behavior

I expected the search results to update in real-time as I type in the search bar, providing immediate feedback and making it easier to find notes.

## Actual Behavior

Currently, the search results remain unchanged until the search button is clicked, requiring additional steps to view filtered results. This can be cumbersome and slows down the search process.

**Comment by DevanshS9881** [comment]
Hello !!!! It would be great if you assign this issue to me under GSSoC extd and hactoberfest accepted label

**Comment by theashikagupta** [comment]
Thanks for raising this issue . Assigned @DevanshS9881

**Comment by raj-adi00** [comment]
Can you assign it to me
