### ISSUE TITLE
[feat]  Implement Undo Functionality for Deleting Notes

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#179]
# Issue Template

## Description
Currently, when users delete notes, the action is permanent and cannot be reversed. To improve the user experience, we need to implement an Undo functionality similar to Google Keep, allowing users to restore notes shortly after deletion. This feature will prevent accidental data loss and make the deletion process more user-friendly.

## type of changes : 
- feature added

## Acceptance Criteria:
- Users should see an Undo option after deleting notes.
- Notes should only be marked as "deleted" and not removed permanently from the database.
- If the user clicks Undo, the notes should be restored without refreshing the page.
- After the undo window (e.g., 5 seconds) expires, the deleted notes remain marked as "deleted" but are not yet hard deleted.

## screenshots
[Screencast from 2024-10-14 10-31-38.webm](https://github.com/user-attachments/assets/ec46749e-e70c-49b0-b1f5-7a5af8351671)

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Thanks for raising this issue @Saurabhchaudhary9799  . You can work on this issue.
