### ISSUE TITLE
Add contact us page 

### ISSUE THREAD

**Issue by theashikagupta** [Scribbie-Notes/notes-app#181]
# Issue Template

## Description

Create a contact us section for homepage and attach with the contact us button on navbar.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to homepage
2. Click on contact us button in navbar
3. See blank page.

## Expected Behavior

When you click on contact us , contact us page should be there.## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add this email : yashmandi18@gmail.com

**Comment by Harmeet10000** [comment]
Hey @theashikagupta , could you please assign this to me?

**Comment by keys-i** [comment]
Can I work in this?
Will there only be a email or a full form for the same?

**Comment by theashikagupta** [comment]
Assigned @Harmeet10000

**Comment by Harmeet10000** [comment]
@theashikagupta i am unable to clone the project as the size is exceeding the git limit, so please assign it to @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799

**Comment by SaanyaGarg5** [comment]
you can assign this task to me ... 
i can design a very good contact page..
