### ISSUE TITLE
[Feat] Support for Pinning and Unpinning Multiple Notes Simultaneously

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#183]
## Description
This PR introduces the ability to pin or unpin multiple notes at once, enhancing the user experience by streamlining note management. Users can now select multiple notes and apply the pin or unpin action in a single operation, saving time and improving workflow efficiency.

## Type of change :
-feature added

## Benefits
**Increased Efficiency**: Users can manage multiple notes in fewer steps, significantly improving the user experience when working with large numbers of notes.
**Improved Usability**: The interface is more intuitive for users who need to manage their notes in bulk.

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , I want to work on this issue,  could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
