### ISSUE TITLE
div size is not aligned with other ones !

### ISSUE THREAD

**Issue by 2004pra** [Scribbie-Notes/notes-app#185]
the size of one of the divs is not same and matched with other div

assign me this under gssoc extd24, hactober fest
## Steps to Reproduce

1. Go to  your website -->https://scribbie-notes.vercel.app/
3. Scroll down to --> hear from our happy customers section
4. See some divs are not aligned 

## Expected Behavior
 they all should be aligned

## Screenshots
not aligned screenshots--> 
![Screenshot 2024-10-14 203903](https://github.com/user-attachments/assets/40f97639-9c4b-43f6-b644-552cabc3f501)

**Comment by theashikagupta** [comment]
Assigned @2004pra

**Comment by 2004pra** [comment]
i am not able to do this issue because i dont know much about react so i am closing this!
