### ISSUE TITLE
I'd like to add scroll animation feature for the homepage.

### ISSUE THREAD

**Issue by varma-101** [Scribbie-Notes/notes-app#188]
Implement smooth scroll animations on the homepage sections using Framer Motion. The animations should trigger as the user scrolls through different sections, adding a dynamic visual effect. Key animations could include fading in, sliding up/down, or zooming in elements as they enter the viewport. Ensure the scroll animations are responsive and work seamlessly across all devices.

**Comment by theashikagupta** [comment]
Assigned

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by varma-101** [comment]
@theashikagupta  i am also working in gsap also to make previous animations display whenever we scroll over it.
Also the navbar is displaying 3 times on homepage because we used pricing and testimonial pages there i also wanted to fix these issues i'll try my best.

**Comment by varma-101** [comment]
I've already started working on these issues,  Please consider the changes i've working and consider giving a level 3 if you are willing to. i also mention detailed changes i've made.
