### ISSUE TITLE
Add Express rate limiter middleware to enhnace security

### ISSUE THREAD

**Issue by 17arindam** [Scribbie-Notes/notes-app#191]
# Issue Template

## Description

i want to add a Express rate limiter middleware to login api which limits the rate of call to the api by this any brute force attacks
can be avoided

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

login

## Expected Behavior

you should not have more than 5 attempt in a duration of 5 mins

## Actual Behavior

Prevents Brute Force Attacks
Reduces Server Load
Protects Against Bots

**Comment by yashmandi** [comment]
thank you for raising this issue, but currently we're not planning this feature ;)
