### ISSUE TITLE
Feature: Add OTP Verification for User Phone Number

### ISSUE THREAD

**Issue by Agnish1611** [Scribbie-Notes/notes-app#193]
## Description

Currently, the phone number field in the user profile allows users to input any number without any validation or verification. This could lead to users entering invalid or incorrect phone numbers, potentially causing issues in case we need to contact them or send important notifications.

## Proposed Solution: 

- Implement an OTP (One-Time Password) based phone number verification system.
- Once a user adds or updates their phone number, send a verification OTP to the provided number.
- The user will need to enter the OTP to successfully verify their phone number.
- Only after verification should the phone number be considered valid and saved to the user profile.

Please assign this issue to me and add the necessary tags.

**Comment by yashmandi** [comment]
thanks for raising this issue, but this is not required at the moment, ;)
