### ISSUE TITLE
[Feat] Add Archiving Notes Functionality

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#194]
# Issue Template

## Description
We would like to add a new feature that allows users to archive their notes. This will enable users to store notes that are no longer actively needed without deleting them permanently.

## Type of change : 
- feature request

## Acceptance Criteria:
- Add an "Archive" option for each note.
- Archived notes should be moved to a separate "Archived Notes" section.
- Users should be able to unarchive notes, returning them to the main notes list.
- Ensure that archived notes are not displayed in the active notes section.
- Add visual distinction (e.g., a label or color) for archived notes.

**Comment by theashikagupta** [comment]
Assigned
