### ISSUE TITLE
Dynamic Messages

### ISSUE THREAD

**Issue by prateek2102** [Scribbie-Notes/notes-app#20]
Currently we have hard coded the error messages and messages in our index.js file, We can create a constants.js file and add all messages there and export them and call them dynamically in our code, this way we will need to update the error messages only in constants.js file and it will be reflected everywhere where we have called them unless we will need to change everywhere. this is also a good approach to begin with. 
Reference - 
![image](https://github.com/user-attachments/assets/87638a52-de62-46ae-889e-a692ba1f63ea)

**Comment by prateek2102** [comment]
@theashikagupta please assign it to me, i would like to work on this part.

**Comment by theashikagupta** [comment]
Assigned to you ! Kindly attach screenshot/screen recording in pr.

**Comment by prateek2102** [comment]
@theashikagupta This issue has been resolved under #42 , please verify and merge. 
Sample dynamic msgs - 
![Screenshot from 2024-10-02 20-24-16](https://github.com/user-attachments/assets/3fb03dc0-ec62-4d5a-9bb5-92596233ad98)
