### ISSUE TITLE
[Feat] Make Active Route Link Color Distinct

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#206]
# Issue Template

## Description
Currently, the active route link does not have a unique color, making it hard for users to identify which page they are on. To improve user experience and navigation, we should implement a different color for the active route link.

## Type of change
- feature request

## screen recording of issue
[Screencast from 2024-10-17 13-22-59.webm](https://github.com/user-attachments/assets/6a2aa792-3030-4835-a23f-ffb58b231c64)

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
