### ISSUE TITLE
Add Help & Support Page

### ISSUE THREAD

**Issue by Prathameshzad** [Scribbie-Notes/notes-app#208]
# Issue Template

## Description
When a user clicks on the Help and Support section in the footer, it should redirect to it. For redirecting there should be a help and support page. So I will be create a help and support page.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'home'
2. Scroll down to 'bottom'
3. Click on "help and support"

## Expected Behavior

When a user clicks on the help and support section from the footer then the user should be redirected to help and support for that there should be a help and support page.

## Actual Behavior
When a user clicks on the Help and Support section in the footer it is not redirecting to help and support section

**Comment by yashmandi** [comment]
thanks for raising the issue, but currently we're not planning this feature on Scribbie ;)
