### ISSUE TITLE
[FEAT] add tooltips on hover 

### ISSUE THREAD

**Issue by yashmandi** [Scribbie-Notes/notes-app#21]
on hovering on pin icon, edit icon and delete icon, it should display what it means, adding tooltip would indicate what each icon mean
![image](https://github.com/user-attachments/assets/232d57c2-81bd-4c86-9446-155906ef67a3)

**Comment by alaminriseuplabs** [comment]
@yashmandi can you assign it to me?

**Comment by AlaminPu1007** [comment]
@yashmandi  could you please assign it to me?

**Comment by AlaminPu1007** [comment]
@yashmandi  could you please assign this to me?

**Comment by theashikagupta** [comment]
Assigned to you ! Go ahead @AlaminPu1007

**Comment by Aryan-dev-enth** [comment]
@yashmandi I reviewed the project and I’m interested in taking on this assignment. Could you please assign it to me?
