### ISSUE TITLE
create contact us page

### ISSUE THREAD

**Issue by Aditya-edith** [Scribbie-Notes/notes-app#212]
# Issue Template
can create a contact us page 

## Description
on clicking contact us it is redirecting to about us i can create another page which will redirect to that page 
## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

Describe what you expected to happen.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
![image](https://github.com/user-attachments/assets/61596697-a266-4e52-a939-fae84e9f3838)
