### ISSUE TITLE
issue in frontend attached video nav is multiple times

### ISSUE THREAD

**Issue by Aditya-edith** [Scribbie-Notes/notes-app#213]
# Issue Template
navbar is multiple times in frontend home section

## Description

A clear and concise description of what the issue is. Include any relevant information such as version, environment, or conditions where the issue was observed.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

Describe what you expected to happen.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

Uploading scribbieU!.mp4…

**Comment by theashikagupta** [comment]
Make a new issue with detailed explaination @Aditya-edith
