### ISSUE TITLE
Addition of back button to signup page and login page

### ISSUE THREAD

**Issue by Shirisha-16** [Scribbie-Notes/notes-app#217]
# Issue Template

## Description

Addition of back button to reach homepage from signup and login page.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'Signup/login page'
2. Click on 'Backbutton'
3. Scroll down to 'Home page'

## Expected Behavior

Describe what you expected to happen.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots
![Screenshot 2024-10-18 195152](https://github.com/user-attachments/assets/48b8675f-a989-4b7f-9095-bab43204f2bb)
I want to work on this issue
@yashmandi assign me this work with the labels gssoc-ext, hacktoberfest-accepted and level according to the issue

**Comment by theashikagupta** [comment]
No need for this @Shirisha-16
