### ISSUE TITLE
Fixing the ui of login and Sign Up button 

### ISSUE THREAD

**Issue by AADESHak007** [Scribbie-Notes/notes-app#220]
# Issue Template

## Description

Login and Sign Up button are very weak in terms of Ui  .

## Actual Behavior
The Ui of the buttons make them look like texts . I want to change the Ui of the buttons and want to add hover effect on it while keeping in mind the UI of the website .
## Screenshots

If applicable, add screenshots to help explain the issue.
![Screenshot 2024-10-18 221942](https://github.com/user-attachments/assets/b9d93002-6b88-4f23-83d4-8862ee829e2b)

Please assign this issue to me under GSSOC and hacktoberfest24

**Comment by yashmandi** [comment]
merged under #222 , hence closing
