### ISSUE TITLE
Improving the UI of the about us page 

### ISSUE THREAD

**Issue by AADESHak007** [Scribbie-Notes/notes-app#221]
# Issue Template

## Description
The about us page looks very simple . Its like as if CSS is not used in it. 
I want to enhance the UI of the About Us Page a bit  .
I won't be altering anything that goes beyond  the theme  of the website  

Please assign this issue to me  .

**Comment by theashikagupta** [comment]
Assigned @AADESHak007

**Comment by yashmandi** [comment]
merged under #230
