### ISSUE TITLE
Bug: After creating a note, tags are not getting updated

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#223]
# Issue Template

## Description

After creating a note, the tags associated with the note do not update correctly

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to the notes app homepage.
2. Click on the "Add Note" button.
3. Enter the note content and add tags in the provided field.
4. Click on the "Save" button.
5. Observe the tags section after the note is created.

## Expected Behavior

The tags associated with the newly created note should be displayed correctly in the tags section immediately after saving the note.

## Actual Behavior

After creating the note, the tags do not appear in the tags section, and the tags list remains unchanged.

## Screenshots

![Animation4](https://github.com/user-attachments/assets/011ad19c-5cad-4dad-9823-1419d9f0a730)

## Additional Context

N/A

**Comment by yashmandi** [comment]
assigned @mehul-m-prajapati
