### ISSUE TITLE
Bug: Create Note app goes out of screen (Not responsive)

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#225]
# Issue Template

## Description

The Create Note pop-up goes out of the screen, making it unresponsive and difficult to use on smaller devices. 

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Open the notes app on a mobile device or resize the browser window to a smaller width.
2. Click on the "Add Note" button to open the Create Note pop-up.
3. Observe the positioning of the pop-up on the screen.

## Expected Behavior

The Create Note pop-up should be fully visible and responsive, allowing users to enter note content and tags without scrolling off-screen.

## Actual Behavior
The Create Note pop-up extends beyond the screen boundaries, requiring users to scroll or resize the window to access all input fields, which hampers usability.

## Screenshots
![Capture](https://github.com/user-attachments/assets/d45ac137-e18d-432b-9880-a28b72b5d82e)

If applicable, add screenshots to help explain the issue.

## Additional Context

NA

**Comment by mehul-m-prajapati** [comment]
@yashmandi : please assign this to me

**Comment by theashikagupta** [comment]
Thanks for raising this issue . Assigned @mehul-m-prajapati
