### ISSUE TITLE
feature: Add un-archive option for archived notes

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#226]
## Description

- Request to add an un-archive option for archived notes. Currently, users can archive notes but have no way to easily restore them to the active notes list
- Add an "Un-archive" button next to each archived note in the archive section. When clicked, the note should be moved back to the active notes list, making it easily accessible again.

## Screenshots

![c2](https://github.com/user-attachments/assets/64998ede-713b-4aaa-b4c1-ca0ef10900be)
## Additional Context

Add any other context or information about the issue here.

**Comment by mehul-m-prajapati** [comment]
@yashmandi : please assign this to me

**Comment by theashikagupta** [comment]
Thanks for raising this issue . Assigned @mehul-m-prajapati
