### ISSUE TITLE
Bug: Delete note is not working for archived notes

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#227]
# Issue Template

## Description

The delete note functionality is not working for archived notes. Users are unable to delete notes that have been archived,

## Steps to Reproduce

1. Go to the notes app homepage.
2. Navigate to the archived notes section.
3. Select an archived note.
4. Click on the "Delete" button.
5. Observe the outcome.

## Expected Behavior
The selected archived note should be deleted permanently from the archive and removed from the notes app.
Describe what you expected to happen.

## Actual Behavior
When attempting to delete an archived note, nothing happens, and the note remains in the archived section.

## Screenshots
![Animation2](https://github.com/user-attachments/assets/b8110038-c3dc-4d8d-b37a-0e96d9520c0a)

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

**Comment by mehul-m-prajapati** [comment]
@yashmandi : please assign this to me

**Comment by theashikagupta** [comment]
Thanks for raising this issue . Assigned @mehul-m-prajapati
