### ISSUE TITLE
[Bug]Note Creation Modal Exceeds Screen Height

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#229]
# Issue Template

## Description
The note creation modal in the dashboard is currently larger than the screen height, as shown in the attached screenshot. This makes it difficult for users to scroll and access all the fields and buttons, especially on smaller screens or devices with limited vertical space.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:
- Navigate to the dashboard.
- Open the note creation modal.
- Observe that the modal exceeds the screen height, requiring excessive scrolling or hiding parts of the form.

## Expected Behavior
The note creation modal should be responsive and adjust to the screen size, either by:
- Adjusting its height to fit within the screen, or
- Adding internal scroll behavior to ensure all fields and buttons are accessible without overflowing the viewport.

## Actual Behavior
the note creation model is bigger than size and all fields and buttons are not accessible.

## Screenshots
![Screenshot from 2024-10-19 10-39-38](https://github.com/user-attachments/assets/037d4916-2cd8-45d9-b1ce-3898fe42f83c)

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta @yashmandi , could you please assign this to me ?

**Comment by mehul-m-prajapati** [comment]
Duplicate issue #225.
This is your 1st warning. Next time, I will report you to program manager

**Comment by Saurabhchaudhary9799** [comment]
> Duplicate issue #225. This is your 1st warning. Next time, I will report you to program manager

@mehul-m-prajapati , i didn't notice before that you created this issue.

**Comment by Saurabhchaudhary9799** [comment]
@mehul-m-prajapati , thank you for pointing this out. I apologize for creating the duplicate issue by mistake
