### ISSUE TITLE
Add tag button not working properly

### ISSUE THREAD

**Issue by Aryan-dev-enth** [Scribbie-Notes/notes-app#23]
![image](https://github.com/user-attachments/assets/ece7ad79-cd56-4133-81fb-29bd1bec1f42)

It should be clicked on the whole button, but right now it's applied to only the plus icon.

**Comment by Aryan-dev-enth** [comment]
@yashmandi assign me this issue and I will fix it.

**Comment by yashmandi** [comment]
you can work on it @Aryan-dev-enth 
attach the screenshots / screen-recordings after changes.

**Comment by Aryan-dev-enth** [comment]
I just raised the PR you may check!
