### ISSUE TITLE
feature: Add filter options above to i can toggle via tags

### ISSUE THREAD

**Issue by RishabhRawatt** [Scribbie-Notes/notes-app#232]
### Description

Requested to add a filter toggle for tags in notes. This feature will allow users to filter notes by matching tag filters.

### How to Use

1. Go to the notes page.
2. Enable the filter toggle.
3. Select the desired tags to filter the notes.

## Additional Context

Add any other context or information about the issue or feature request here.

**Comment by RishabhRawatt** [comment]
can you please assign this to me /assign

**Comment by theashikagupta** [comment]
Thanks for rasing this issue . Assigned @RishabhRawatt

**Comment by yashmandi** [comment]
closed under #250
