### ISSUE TITLE
[BUG] Feedback Form Not Functioning Properly

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#237]
# Issue Template

## Description
The feedback form on the website is currently not functioning as expected. Users are unable to submit their feedback, and no confirmation or error messages are displayed. This issue affects the overall user experience and may prevent us from receiving valuable user feedback.

## Steps to Reproduce
Please provide step-by-step instructions on how to reproduce the issue:
1. Navigate to the feedback form page.
2. Fill out the feedback fields (name, email, message, etc.).
3. Click the "Submit" button.
4. Observe that the form does not submit, and there is no confirmation or error message.
5. ## Expected Behavior

Describe what you expected to happen.
Upon submission, the form should:
- Validate the inputs.
- Display either a success message (if submission is successful) or an error message (if validation fails or the server encounters an issue).
- Send the form data to the backend for processing.

## Actual Behavior

- The form does not submit, and no message (success or error) is shown to the user.
- Feedback data is not sent to the backend.

## Screenshots
[Screencast from 2024-10-20 02-11-05.webm](https://github.com/user-attachments/assets/e4476029-071a-4717-a97e-f374bf07d931)

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta @yashmandi , I want to work on this issue , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
