### ISSUE TITLE
[BUG] Login and Signup Buttons Displayed When User is Logged In

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#239]
# Issue Template

## Description
Currently, when a user is logged in, the Login and Signup buttons are still visible in the header. Clicking on either button redirects to their respective pages, which should not happen if the user is already authenticated. This creates confusion and affects the user experience.

## Steps to Reproduce
Please provide step-by-step instructions on how to reproduce the issue:
- Log in with a valid account.
- Once logged in, observe the header — the Login and Signup buttons are still displayed.
- Click on the Login or Signup button in the header.
- You are redirected to the login or signup page despite being logged in.

## Expected Behavior
- When a user is logged in, the Login and Signup buttons should be hidden or replaced with other options (e.g., profile link or logout button).
- Clicking the login or signup links should not redirect authenticated users to the login or signup page.

## Actual Behavior
- The Login and Signup buttons remain visible even after logging in.
- Clicking on these buttons redirects the user to the respective login/signup page, although they are already logged in.

## Screenshots
[Screencast from 2024-10-20 02-31-16.webm](https://github.com/user-attachments/assets/87a731f3-c117-4def-89aa-88ac98ea2a7d)

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
