### ISSUE TITLE
[FEAT] Limit the characters of the title and body of the notes

### ISSUE THREAD

**Issue by yashmandi** [Scribbie-Notes/notes-app#24]
when the user creates a new note. the title should be under 60 characters, and the body of the note should be under 2500 characters. also display it at the end of the text box.
![Screenshot](https://github.com/user-attachments/assets/a27445ec-a1c0-4a16-b80d-dda384f90a92)

**Comment by ptskok** [comment]
Hello, can you assign me?

**Comment by ptskok** [comment]
@yashmandi 
Hello, can you assign me?

**Comment by theashikagupta** [comment]
Assigned to you! @ptskok

**Comment by ptskok** [comment]
Hello @theashikagupta and @yashmandi , i have created a [PR](https://github.com/Scribbie-Notes/notes-app/pull/83)

**Comment by yashmandi** [comment]
merged under #83 , hence closing
