### ISSUE TITLE
[FIX] adjust the alignment

### ISSUE THREAD

**Issue by yashmandi** [Scribbie-Notes/notes-app#25]
on searching any random note / note content that does not exists, the image of "Oops! No notes found matching" is slightly at the left side, make it at the center, also make sure it is working well in mobile screen devices. 
kindly add the screenshots after making changes.
![Screenshot](https://github.com/user-attachments/assets/822514e0-cbd1-48ac-b637-5af6f718f294)

**Comment by bulutyerli** [comment]
i can work on this, can you assign this to me?

**Comment by bulutyerli** [comment]
@theashikagupta I have made a PR for the delete account feature. I have fixed this one too, if you assign this one i will create a pr directly.

**Comment by theashikagupta** [comment]
Assigned to you! @bulutyerli

**Comment by PraveenUppar** [comment]
I will resolve the issue #25 assign me the work @theashikagupta

**Comment by Karan-Mahato** [comment]
I would like to work on issue #25

**Comment by akashsiripuram** [comment]
I would like to work on issue #25.

**Comment by theashikagupta** [comment]
Assigned to @PraveenUppar !

**Comment by yashmandi** [comment]
solved under #88 
hence closing
