### ISSUE TITLE
Providing mic option for the user to enter content of the notes.

### ISSUE THREAD

**Issue by AkashD625** [Scribbie-Notes/notes-app#256]
# Issue Template

## Description
When adding a mic option for users to dictate the content of notes, the feature is expected to convert spoken words into text in real time.

## Steps to Reproduce

Go to the 'Add/Edit Note' section.
Click on the microphone icon to start dictating.
Begin speaking to enter the content of the note.
Observe if the spoken words are converted into text.

## Expected Behavior
The user should be able to click the mic button, dictate the content, and see the real-time transcription appear in the note content field.

## Actual Behavior
Easy for the user to add his notes .

## Screenshots

User faces very difficulty while entering the notes , if the size of the notes are to big then its so hard and time consumming for the uers to add.
This mic functinality will make this problem solved.

## Additional Context
Add any other context or information, such as browser compatibility, microphone access permissions, or errors shown in the console, that might be relevant to the issue.

**Comment by theashikagupta** [comment]
Assigned @AkashD625

**Comment by AkashD625** [comment]
Thankyou .

**Comment by AkashD625** [comment]
Thankyou @theashikagupta

**Comment by yashmandi** [comment]
merged under #274
