### ISSUE TITLE
Feat: Contact Us backend

### ISSUE THREAD

**Issue by harshbhar0629** [Scribbie-Notes/notes-app#257]
# Issue Template

## Description
There is no backend use in contact us page.

## Expected Behavior
When user enter their own detail and click to send then that info will be send  to the admin of website and also give the toast of sending successfully message.

## Actual Behavior
Now when we click on send btn then nothing will happend.

@theashikagupta Please assign this issue to me:)

**Comment by theashikagupta** [comment]
Assigned @harshbhar0629
