### ISSUE TITLE
Adding framer Motion to Home Page

### ISSUE THREAD

**Issue by Bhum-ika** [Scribbie-Notes/notes-app#259]
## Description

The website will look more appealing and attractive after adding framer motion

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by yashmandi** [comment]
thank you for raising the issue, but currently the animations have been already implemented in the home page.
if you can enhance it in a better way, you can go ahead, if so, kindly explain what would you enhance. ;)
