### ISSUE TITLE
[FEAT] user should be able to update his name

### ISSUE THREAD

**Issue by yashmandi** [Scribbie-Notes/notes-app#26]
add a button next to name of the user as "update name" button (similar to "change email" button).
on clicking on this "update name" button, a modal should appear, where the user should enter the new name / updated name he wants to update, and hit the save button.
on saving, the name should get updated and should start reflecting in frontend, and shold also updated on backend database as well.
try to keep modal and button theme same as other buttons & modals.
after completion, kindly add screenshots or video recording demonstrating the changes made.
![Screenshot](https://github.com/user-attachments/assets/acfe1d94-315f-403f-bc84-cf68d22379c3)

**Comment by perig99** [comment]
Hello @yashmandi, I would like to contribute on this issue. :)

**Comment by itznayan** [comment]
hey, @yashmandi , i will like to work on this issue under GSSOC'24 and Hackerfest .

**Comment by theashikagupta** [comment]
Assigned to you ! @perig99

**Comment by itznayan** [comment]
hey @theashikagupta  @yashmandi  please approve this PR . i have solved this issue 

https://github.com/user-attachments/assets/2b423478-2b9f-4065-b8d1-99f2f3c39969

**Comment by itznayan** [comment]
hey @theashikagupta  @yashmandi  please approve this PR . i have solved this issue.

**Comment by itznayan** [comment]
My contribute not showing in leaderboard the label should be level2 please remove space from labels level 2 is incorrect.

**Comment by theashikagupta** [comment]
I have already made corrections . @itznayan
