### ISSUE TITLE
[Bug] updating note functionality is not working

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#260]
# Issue Template

## Description
The updating functionality in the application is currently not working as expected. When attempting to update [data/post/profile/etc.], the changes are not being reflected in the UI or the database.

## Steps to Reproduce
Please provide step-by-step instructions on how to reproduce the issue:
1. Navigate to Home page.
2. Attempt to update note.
3. Submit the update request.

## Expected Behavior
The updated information should be reflected immediately in the UI and stored correctly in the database.

## Actual Behavior
The UI does not display the updated information, and it appears that the update request is not processed or saved in the database.

## Screenshots
[Screencast from 2024-10-22 18-06-48.webm](https://github.com/user-attachments/assets/47488bf3-628a-4077-a755-725bdb3f93f6)

**Comment by mehul-m-prajapati** [comment]
already fixed #224

**Comment by Saurabhchaudhary9799** [comment]
@mehul-m-prajapati , it is not working on my local machine after your merged  PR, then I created issue
