### ISSUE TITLE
Account deletion feature in the settings menu

### ISSUE THREAD

**Issue by RiyaBhurse** [Scribbie-Notes/notes-app#269]
When a user clicks on the "Delete My Account" option in the settings, no immediate feedback or redirection occurs. After account deletion, the user should be redirected to the login page or provided with feedback that their account has been successfully deleted.
please assign this issue to me with hacktoberdefest tag and gssoc tag

**Comment by yashmandi** [comment]
thanks for raising the issue, but currently when the user logs out, the user can see a toast notification that he's been logged out.
