### ISSUE TITLE
[BUG] delete account button not working in backend

### ISSUE THREAD

**Issue by yashmandi** [Scribbie-Notes/notes-app#27]
on clicking on delete account button in my account section, it works fine in frontend, but does not gets actually deleted in backend.
if user clicks on delete account button, make sure it also gets deleted in backend database, and all the notes, data, related to that user shoudl also get deleted in backend. and then he should be routed to home page after successful deletion.
![Screenshot](https://github.com/user-attachments/assets/cd410537-d0a1-4c32-a292-b0e020218738)

**Comment by bulutyerli** [comment]
i can work on this, can you assign this to me?

**Comment by theashikagupta** [comment]
Assigned to you! @bulutyerli

**Comment by shubham-mehta-002** [comment]
I can work on this issue

**Comment by theashikagupta** [comment]
@shubham-mehta-002  Assigned to you!
