### ISSUE TITLE
Bug: Missing scrollbar in create new note pop up 

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#275]
# Issue Template

## Description
There is a missing scrollbar in the "Create New Note" pop-up, making it difficult to access content if it exceeds the visible area

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Open the application.
2. Click on the "Create New Note" button.
3. Enter content that exceeds the visible area of the pop-up.
4. Attempt to scroll down to view all content.

## Expected Behavior

A scrollbar should appear in the pop-up, allowing users to scroll through and view all content.

## Actual Behavior

A scrollbar should appear in the pop-up, allowing users to scroll through and view all content.

## Screenshots

![Capture](https://github.com/user-attachments/assets/ea41b9aa-5e59-4ed2-b337-4473899cf4cd)
## Additional Context

Add any other context or information about the issue here.

**Comment by theashikagupta** [comment]
Assigned @mehul-m-prajapati
