### ISSUE TITLE
Bug: Hard coding of backend server URL causing failure of many requests

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#276]
# Issue Template

## Description

The backend server URL is hard-coded in the application, leading to failures in various requests when the server address changes

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Open the application in a development or staging environment.
2. Attempt to perform any action that requires a backend request (e.g., fetching notes, saving a note).
3. Observe the error message indicating that the server cannot be reached.

## Expected Behavior

The application should dynamically use the appropriate backend server URL based on the environment, allowing successful requests without hard-coded values.

## Actual Behavior

Requests fail due to the hard-coded backend server URL, resulting in error messages and an inability to interact with the backend.

## Screenshots

![c1](https://github.com/user-attachments/assets/44cdda5d-eaf4-4288-90da-ab973541e64a)
## Additional Context

Add any other context or information about the issue here.

**Comment by theashikagupta** [comment]
Assigned @mehul-m-prajapati
