### ISSUE TITLE
.env Files Being Uploaded to the Codebase

### ISSUE THREAD

**Issue by OINDIL** [Scribbie-Notes/notes-app#28]
### Problem:
The .env files, which contain sensitive configuration data, are being mistakenly uploaded to the codebase. This is exposing critical information such as API keys, database credentials, and other secrets.

### Expected Behavior:
.env files should be excluded from the repository to prevent accidental exposure of sensitive data. This is typically done by adding the .env file to the .gitignore file.

**Comment by yashmandi** [comment]
go ahead @OINDIL , work on it ;)
