### ISSUE TITLE
you have error in the backend

### ISSUE THREAD

**Issue by AyushSharma72** [Scribbie-Notes/notes-app#280]
i saw a error in the backend

![image](https://github.com/user-attachments/assets/20809f81-d8f5-4ff4-883f-0f24536032d3)

i also sync my fork 
![image](https://github.com/user-attachments/assets/06897b24-e22d-46b5-81e3-7c75baf9c8c7)

please assign me to resolve the error @yashmandi

**Comment by mehul-m-prajapati** [comment]
Duplicate issue #278
