### ISSUE TITLE
[bug] search functionality is not working

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#283]
# Issue Template

## Description
The search feature is currently malfunctioning, leading to inaccurate or no results being displayed when users try to search for notes. This impacts the user experience by making it difficult to find relevant information.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'Home page'
2. write note title in search bar
3. click on search button

## Expected Behavior
- When a user enters a valid query in the search bar, the results should display only the items that are relevant to the search term.
- The search should accurately filter the content based on the query and provide results quickly and reliably.

## Actual Behavior
- When a user enters a query in the search bar and submits, either no results are returned or the results do not match the query.
- In some cases, the search returns unrelated results or fails to filter data correctly.

## Screenshots
[Screencast from 2024-10-24 16-20-48.webm](https://github.com/user-attachments/assets/80b5bffb-4982-464f-a792-04960dc83b7d)

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta @yashmandi , I want to work on this issue. Could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799
