### ISSUE TITLE
set proper url of the backend

### ISSUE THREAD

**Issue by AyushSharma72** [Scribbie-Notes/notes-app#285]
most of your api calls have wrong api url 
like this one in the contact form 

![image](https://github.com/user-attachments/assets/1c9cffd8-3346-4c69-bcc6-e18333caef9c)

i want to fix these url so that correct request can be made to the backend api
please assign this issue to me @theashikagupta

**Comment by theashikagupta** [comment]
Assigned @AyushSharma72
