### ISSUE TITLE
the navbar is not responsive

### ISSUE THREAD

**Issue by AyushSharma72** [Scribbie-Notes/notes-app#286]
you navbar is not responsive i want to add a hamburger icon for small screen 
the un responsive navbar is making the other pages un responsive

![image](https://github.com/user-attachments/assets/0848b514-6cc7-4d36-b73a-5f2e989ac45a)

please assign this issue to me @theashikagupta

**Comment by Venkateeshh** [comment]
i would like to work on this issue please assign me this issue

**Comment by theashikagupta** [comment]
Assigned @AyushSharma72

**Comment by zaheer-Khan3260** [comment]
hey @AyushSharma72  i have great experiance with these kind of problem. please assign it to me. I am start working on it.
