### ISSUE TITLE
[doc] want to  add Complete this process in GitHub(using markdown)

### ISSUE THREAD

**Issue by REHAN-18** [Scribbie-Notes/notes-app#300]
# Issue Template

## Description

like this I want to add in the readme which help the contributor to understand the process (is will be done by markdown with functional like zoom up work, downward etc .. we can control )
<img width="810" alt="Screenshot 2024-10-26 at 3 52 06 PM" src="https://github.com/user-attachments/assets/c779beda-df5e-4e15-9ff3-0136ea2ddef7">
it helps the contributor to learn how to contribute 

@yashmandi @theashikagupta pls assign me

**Comment by yashmandi** [comment]
thank you for raising the issue, currently, there are proper steps to contrubute to this project in readme, so i think there's no need in this ;)

**Comment by REHAN-18** [comment]
@yashmandi 
yes but I will enhance the repo readme
