### ISSUE TITLE
Add loading sign when application gets loaded

### ISSUE THREAD

**Issue by Anshikapal05** [Scribbie-Notes/notes-app#303]
# Issue Template

## Description

Add a loading indicator that displays while the application is loading, providing users with visual feedback until the content is fully rendered.This enhances user experience by clearly signaling that content is being fetched, reducing uncertainty during load times.
It is done to enhance the UI and will look good.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to site'
2. See loading.

## Expected Behavior

When the application is opened, a loading indicator (e.g., spinner or progress bar) should appear immediately, signaling that the app is processing or fetching data. The loading indicator should remain visible until all essential content is fully loaded and ready for user interaction, at which point it should disappear smoothly, allowing the user to engage with the application seamlessly.

## Actual Behavior

When the application is opened, a loading indicator which will enhance the UI

**Comment by Anshikapal05** [comment]
@yashmandi kindly assign this issue to me. Would be really great of you.
Thank you

**Comment by yashmandi** [comment]
thanks for raising the issue, but there's already a loading animation when the page loads ;)
