### ISSUE TITLE
[bug] tags are being displayed in array not  in separate blocks

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#305]
# Issue Template

## Description
This issue is related to tags . when user is adding or updating tags in notes. They are being displayed in very different manner such as in array. But they should be displayed in separate blocks.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'Home page'
2. Click on 'create button' or 'update button'
3. add tags 

## Expected Behavior
the tags should be displayed in separate blocks.

## Actual Behavior
they are being displayed in array like #["code","node"] .

## Screenshots
[Screencast from 2024-10-26 18-21-52.webm](https://github.com/user-attachments/assets/6d8a1c17-7bfe-4a34-a9d4-cf002f28e3d5)

**Comment by Saurabhchaudhary9799** [comment]
@yashmandi @theashikagupta  , could you please assign this to me ?

**Comment by theashikagupta** [comment]
Assigned @Saurabhchaudhary9799

**Comment by mehul-m-prajapati** [comment]
@theashikagupta  @yashmandi : This bug was solved in https://github.com/Scribbie-Notes/notes-app/pull/236.

But, merge changes have removed it.
