### ISSUE TITLE
Adding FAQ section

### ISSUE THREAD

**Issue by A2005-beep** [Scribbie-Notes/notes-app#307]
# FAQ

## there is no FAQ section for users to know more about the application.

A clear and concise description of what the issue is. Include any relevant information such as version, environment, or conditions where the issue was observed.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to home page
2. Scroll down to the end of the home page
3. Beside about
4. FAQ

## Expected Behavior

An FAQ section will be added

## Actual Behavior

adding an FAQ will really be helpful for user understanding.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

THANK YOU! please assing me this issue so that i can work on it @yashmandi

**Comment by yashmandi** [comment]
thank you for raising the issue, but there's already an FAQ section so no need of another ;)
