### ISSUE TITLE
[bug] logout functionality is not working properly in each page.

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#308]
# Issue Template

## Description
This issue is related to log out button , when i click on logout in home page , it does not functioning. But in some pages like pricing and profile page , it does not functioning like log out functionality.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'each page'
2. Click on 'profile avatar'
3. click on log out button .

## Expected Behavior
when i click on log out button , it should display a model of confirmation. it should work according to your confirmation.

## Actual Behavior
It is working in some pages but in some page it is not working or has other functionality except log out.

## Screenshots
[Screencast from 2024-10-26 18-31-18.webm](https://github.com/user-attachments/assets/203b9780-a1e8-4000-a7c0-1860aed9ffef)

**Comment by Saurabhchaudhary9799** [comment]
@yashmandi @theashikagupta , could you please assign this to me ?

**Comment by harshbhar0629** [comment]
@yashmandi Can i work on this issue??

**Comment by Saurabhchaudhary9799** [comment]
> @yashmandi Can i work on this issue??

@harshbhar0629 , This issue is assigned to me, I am working on this issue.

**Comment by harshbhar0629** [comment]
Ok Brother:)
