### ISSUE TITLE
Add Automated Greeting Workflow 

### ISSUE THREAD

**Issue by aditiverma-21** [Scribbie-Notes/notes-app#314]
# Issue Template

## Description

I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible.

**Comment by yashmandi** [comment]
thank you for raising the issue, but we're not planning to have this feature currently ;)
