### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [Scribbie-Notes/notes-app#319]
# Issue Template

## Description

The README file is currently very long, making it difficult to quickly reach specific sections. Adding a table of contents would improve navigation.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to CODE Section
2. Scroll down to README Section
4. See that there is no table of contents available

**Comment by Pallavi-Mukalla** [comment]
please assign me this issue

**Comment by yashmandi** [comment]
Thank you for bringing this up. However, we believe the README file should be detailed and more comprehensive to help contributors understand the guidelines and contribution steps clearly.
