### ISSUE TITLE
Bug: Nav bar is not responsive

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#322]
# Issue Template

## Description
Nav bar is not responsive

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to website
2. See navbar in mobile view

## Screenshots

![c4](https://github.com/user-attachments/assets/be8b463f-baa4-4440-906f-7eecee535ac5)
## Additional Context

Add any other context or information about the issue here.

**Comment by mehul-m-prajapati** [comment]
@Saurabhchaudhary9799 : If you are good with front-end, go ahead with this one.

**Comment by Saurabhchaudhary9799** [comment]
> @Saurabhchaudhary9799 : If you are good with front-end, go ahead with this one.

@mehul-m-prajapati , Okay 
@yashmandi , Please assign this to me

**Comment by Saurabhchaudhary9799** [comment]
> > @Saurabhchaudhary9799 : If you are good with front-end, go ahead with this one.
> 
> @mehul-m-prajapati , Okay @yashmandi , Please assign this to me
