### ISSUE TITLE
Bug: Update Note does not work

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#336]
# Issue Template

## Description

- It works until commit: https://github.com/Scribbie-Notes/notes-app/commit/68eba74b8d4d40f5a799d5d0df52562d358d974a. The new changes after that commit have broken many features
- Un-archive notes also not working which is mentioned in https://github.com/Scribbie-Notes/notes-app/issues/332

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to website
2. Click on edit note
3. Scroll down to update note

## Screenshots

![Animation1](https://github.com/user-attachments/assets/a7b6739f-7ae5-4ed8-95c7-412150c06d31)
## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
kindly recheck it & update me again @mehul-m-prajapati , because it is working fine on my end :)

**Comment by mehul-m-prajapati** [comment]
@yashmandi : Here is full diagnosis 💂‍♂️ 

https://github.com/user-attachments/assets/7af7143d-fb19-4ef6-9163-8964723bd581

**Comment by mehul-m-prajapati** [comment]
@yashmandi : Tested on latest commit 7acf1c223ed1a5a39f0e876874d0f0de8a7b4dc8.
It does not work
