### ISSUE TITLE
[FEAT] : Add Contact Us Via E-Mail

### ISSUE THREAD

**Issue by PriyanshuValiya** [Scribbie-Notes/notes-app#346]
# Issue Template

## Description

From this page, user can mail their issue, reviews, and query direct from website. 

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

Describe what you expected to happen.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots

![Screenshot 2024-10-22 210539](https://github.com/user-attachments/assets/1c760301-c2a5-4dbc-a388-d6103e6813ad)

## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
thank you for raising the issue, but currently we already have the contact page, hence this is not required ;)
