### ISSUE TITLE
bug : 404 Page Not Found Error After Deployment

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#36]
### Description:
 When a user refreshes the page after navigating to a specific route, they are redirected to a 404 Not Found page. This issue occurs regardless of whether the user has logged in, signed up, or simply navigated to a page that should be accessible. The lack of proper routing or handling for these page refreshes is causing confusion and hindering user experience.

### Expected Behavior: 
Upon refreshing the page, users should remain on the current page they were viewing or be directed to a default landing page, rather than encountering a 404 Not Found error. Proper routing and state management should ensure that valid pages are accessible even after a refresh.

### Steps to Reproduce:
1. Navigate to any route within the application (e.g., login, signup, dashboard).
2. Refresh the page using the browser's refresh button.
3. Observe that the user is redirected to a 404 Not Found page.

### Proposed Solution:
- Implement proper routing logic to handle page refreshes gracefully.
- Ensure that valid routes are retained in the application's state, so users are directed to the correct pages after a refresh.

**Comment by Saurabhchaudhary9799** [comment]
Hey @theashikagupta , I want to contribute regarding this issue , can you assign this to me

**Comment by theashikagupta** [comment]
Assigned to @Saurabhchaudhary9799 !

**Comment by theashikagupta** [comment]
How much time it will take ? @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , I will complete it by this afternoon.
