### ISSUE TITLE
Bug Fixes for User Registration and Profile Update Functionality

### ISSUE THREAD

**Issue by chikatlarakesh** [Scribbie-Notes/notes-app#37]
**GSSoC Contributor**

_I have encountered several bugs in the user registration and profile update functionality of our Express application. Here’s a summary of the identified issues and proposed solutions:_

### 1. User Registration Password Validation:
_Issue:_ The password validation checks are overly restrictive and may prevent valid passwords.
_Solution:_ Adjust the password validation checks to ensure that users can create strong but valid passwords.

### 2. User Login Validation:
_Issue:_ The user login route doesn't handle incorrect passwords gracefully.
_Solution:_ Ensure that we check for incorrect passwords and return appropriate error messages.

### 3. Updating User Email:
_Issue:_ The update email route allows updating the email to an empty string without validation.
_Solution:_ Add validation to ensure the new email is not empty and follows a valid format.

### 4. Profile Photo Update:
_Issue:_ The file upload feature does not handle errors properly.
_Solution:_ Add error handling for file uploads to provide clearer feedback on failures.

**Comment by ADeshmukh80** [comment]
Please assign this task to me

**Comment by yashmandi** [comment]
you can work on it @chikatlarakesh

**Comment by yashmandi** [comment]
> Please assign this task to me

@ADeshmukh80 the tasks are assigned on first come first serve basis. kindly find any other issue to work on ;)

**Comment by yashmandi** [comment]
completed under #89 
hence closing
