### ISSUE TITLE
Add "Back to Top" Scroll Button in README

### ISSUE THREAD

**Issue by T-Fathima** [Scribbie-Notes/notes-app#373]
# Issue Template

## Description

Add a "Back to Top" button in the README to improve navigation, especially for readers scrolling through long sections. This button will allow users to quickly scroll back to the top of the README without manually scrolling up.

I would like to work on it.
Please assign it to me.

**Comment by yashmandi** [comment]
thankyou for raising the issue, but this is not required as of now
