### ISSUE TITLE
Feature: Add revert note to previous version functionality

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#393]
# Issue Template

## Description
- We can store previous version in memory
- User can revert note to one version
- Version will be lost when page is refreshed

**Comment by mehul-m-prajapati** [comment]
@yashmandi : please assign it to me

**Comment by yashmandi** [comment]
i appreciate your idea @mehul-m-prajapati , but can u please explain more, how can this feature be helpful.

**Comment by mehul-m-prajapati** [comment]
@yashmandi : If you accidentally save note by clearing some data, then this feature will help to restore last version of your note
