### ISSUE TITLE
Feature: Add sort by date in Navbar for notes

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Scribbie-Notes/notes-app#394]
# Issue Template

## Description
Feature: Add sort by date in Navbar for notes
![a1](https://github.com/user-attachments/assets/00c35c05-24ba-4a34-a1e2-f315e5f04197)

**Comment by mehul-m-prajapati** [comment]
@yashmandi : please assign it to me

**Comment by yashmandi** [comment]
![Screenshot](https://github.com/user-attachments/assets/9ef3f23d-1af9-44fa-a0e5-15b977713a69)
can u add it at right top corner, right below the navbar? i think it would look better over there

**Comment by mehul-m-prajapati** [comment]
@yashmandi : okay, done
