### ISSUE TITLE
[ FEATURE REQUEST ] DEPLOYMENT LINK

### ISSUE THREAD

**Issue by Meetpidev** [Scribbie-Notes/notes-app#397]
## Description
DEPLOYME IT AND ADD LINK IN README.md FILE SO THAT WE CAN SEE THE WEBSITE WITHOUT CLONING AND CAN SUGGEST FASTLY..

## Expected Behavior
SHOULD BE DEPLOYED..SO THAT ANYONE CAN SEE AND MAKE SUGATIONS WITHOUT CLONING..

**Comment by Meetpidev** [comment]
@yashmandi Can i do this ??

**Comment by yashmandi** [comment]
thank you for raising this, issue, but currently ther'e are some bugs in deployed link, so we cant add here ;)

**Comment by Meetpidev** [comment]
@yashmandi I can redeploy it if you wish.. i can deploy it in render or vercel
