### ISSUE TITLE
Feature: Personal Finance Dashboard

### ISSUE THREAD

**Issue by Dkghuser** [Scribbie-Notes/notes-app#398]
# Issue Template

## Description

Many existing personal finance tools either lack customizable tracking for personal budgets, investments, and savings goals or require complex integrations. This dashboard provides an all-in-one, simplified solution for tracking and visualizing financial data in real-time. It addresses the common challenge of fragmented financial data management, where users struggle to see a consolidated view of their finances across different categories.

## Steps to Reproduce

Below is the step-by-step instructions on how to reproduce the issue:

1. **Go to** the main page of the Personal Finance Dashboard by opening index.html in the browser.
2. **Click on** the 'Budgeting' section and set a monthly budget (e.g., $1000, to be entered as 1000).
3. **Scroll down or Navigate** to the 'Expense Tracking' section and enter an expense (e.g., category: "Groceries," amount: $50).
4. **See error:** No feedback appears for missing input, or an error message displays unexpectedly in the console. Return to the 'Budgeting' section. Observe the Budget Progress bar or chart.

## Expected Behavior

After adding an expense, the budget progress bar or chart should reflect the updated spending. If a $50 expense was added to a $1000 budget, the budget progress should show $950 remaining.

## Actual Behavior

The budget progress bar or chart does not update, still displaying the original budget amount without considering the recent expense.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
invalid issue
