### ISSUE TITLE
add newsletter subscription option frontend and backend

### ISSUE THREAD

**Issue by AyushSharma72** [Scribbie-Notes/notes-app#400]
i want to add a option in the footer of subscribe to news letter

frontend example :
![image](https://github.com/user-attachments/assets/6d505a3e-d310-4276-b1a4-06f1ba077576)

backend email example :
![Screenshot (121)](https://github.com/user-attachments/assets/2467c809-6758-4a22-b442-fff0f27834cb)

please assign this issue to me  @theashikagupta

**Comment by yashmandi** [comment]
thanks for raising the issue, but currently we're not planning for this feature
