### ISSUE TITLE
adding icon to menu and using illustration for better UX

### ISSUE THREAD

**Issue by itznayan** [Scribbie-Notes/notes-app#44]
There is not icon for menu and there is simple not found message i wanna make it better.

![Screenshot (126)](https://github.com/user-attachments/assets/35eb3ba5-8d47-4c54-9c26-1c0f80e0692a)

**Comment by theashikagupta** [comment]
@itznayan Assigned to you!

**Comment by itznayan** [comment]
@theashikagupta  please provide gssoc'24 extd tag .
