### ISSUE TITLE
feat: modern_footer

### ISSUE THREAD

**Issue by itznayan** [Scribbie-Notes/notes-app#45]
Hello @theashikagupta 

I believe a dedicated Footer is required to make it a brand value . Further including some statements and copyright tag would make it more better . As well including some of your details like , LinkedIn might bring some more network opportunity.

I am a gssoc'24 extd contributor . Please assign this issue to me .

https://github.com/user-attachments/assets/4bfc409b-228c-42b2-9098-1323405865c1

**Comment by theashikagupta** [comment]
Thanks @itznayan for raising this issue . Assigned to you!

**Comment by itznayan** [comment]
@theashikagupta please provide gssoc'24 extd tag and level.

**Comment by itznayan** [comment]
@theashikagupta  please approve PR .

https://github.com/user-attachments/assets/ee2a9b6e-b523-4cb0-b83b-fc701549d453
