### ISSUE TITLE
BUG: Fix the error showing on signup and login .

### ISSUE THREAD

**Issue by theashikagupta** [Scribbie-Notes/notes-app#49]
# Issue Template

## Description

Fix the error showing on signup and login .

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'signup' or login
2. Fill details 
3. Submit

## Expected Behavior

After fill up the details correctly it should signup or login 

## Actual Behavior

Showing error after fillup the details .

## Screenshots

![Screenshot 2024-10-02 215614](https://github.com/user-attachments/assets/24ef4836-6bee-4e8f-a1de-dbf65f654068)

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta  , could you please assign it to me

**Comment by theashikagupta** [comment]
Assigned to you! @Saurabhchaudhary9799

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta ,  i just checked this issue , the signup page is working properly 
[Screencast from 2024-10-02 23-04-55.webm](https://github.com/user-attachments/assets/34a30825-3c59-4458-b0be-48f751a04fe6)

**Comment by itznayan** [comment]
@Saurabhchaudhary9799 fork repository then it will show error.

**Comment by Saurabhchaudhary9799** [comment]
i got it.

**Comment by Saurabhchaudhary9799** [comment]
i will fix this issue

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , it should also working on localhost after fork
[new.webm](https://github.com/user-attachments/assets/f4ceeb2a-9d8c-48c8-b3a2-cdc795e6be08)
please make sure whether your server is connected or not , or this error may occur because of network issue

**Comment by theashikagupta** [comment]
Okay then I closed this issue.

**Comment by itznayan** [comment]
@theashikagupta  ,due to this issue i am not able to work on issue #44  and #26 .is it okay to wait until this issue solve.

**Comment by itznayan** [comment]
@theashikagupta please check PR i have fixed the issue #49 of login and logout.

https://github.com/user-attachments/assets/c78fced4-0c2c-450d-886d-9f0414504ea1

**Comment by Saurabhchaudhary9799** [comment]
hey @yashmandi @theashikagupta , Kindly check my PR

**Comment by theashikagupta** [comment]
@Saurabhchaudhary9799  In my local , signup and login is not working again . Can you please check ?

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , yeah

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , there is lots of error in router.js in my local machine after pull

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , can you tell me what is exact error with the help of screenshots of  backend console

**Comment by theashikagupta** [comment]
![Screenshot 2024-10-24 112027](https://github.com/user-attachments/assets/20034488-13b3-459c-9838-7234efe1dccd)

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , send me screenshots of  backend console also

**Comment by theashikagupta** [comment]
https://github.com/user-attachments/assets/0b6c0b33-2ac3-42c3-91f1-27b4b05eda81

**Comment by Saurabhchaudhary9799** [comment]
@theashikagupta , don't put quotes around string

**Comment by Saurabhchaudhary9799** [comment]
> @theashikagupta , don't put quotes around string

![Screenshot from 2024-10-25 22-32-23](https://github.com/user-attachments/assets/9850eed5-a588-4c58-afe6-1ceacf81c0ca)
