### ISSUE TITLE
bug : Phone Number validation is not working

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#50]
### Description
The mobile number validation is not functioning as expected, allowing invalid numbers to be submitted.

### Steps to Reproduce
- Navigate to user profile.
- Click on **Change Phone** button.
- Enter anything like any string or 5 digit number in input.
- It saves this as your phone number

### Expected Behavior: 
The system should display a validation error message indicating that the mobile number is invalid.

### Actual Behavior: 
The system allows the submission of invalid mobile numbers without any error message.

## Screenshots
[Screencast from 2024-10-02 23-10-13.webm](https://github.com/user-attachments/assets/3ee1a8fd-9132-4688-9263-4bc78c25a699)

### Additional Context: 
This issue may affect users trying to register with an invalid mobile number, leading to potential issues with account verification.

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , could you please assign it to me

**Comment by shubham-mehta-002** [comment]
@theashikagupta 
I can fix this

**Comment by theashikagupta** [comment]
Assigned to @Saurabhchaudhary9799 !

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta , Kindly check this PR
