### ISSUE TITLE
Implement Sticky Navbar Visibility on Scroll

### ISSUE THREAD

**Issue by anamelahi** [Scribbie-Notes/notes-app#53]
## Description

Current Behavior:
The navbar is not visible when the user scrolls down the page. In order to access the navbar, users must scroll back to the top of the website.

## Steps to Reproduce

1. Go to the website
2. Scroll down
3. See error

## Expected Behavior

- The navbar should reappear when the user scrolls up, providing quick access to navigation without needing to return to the top of the page.
- The navbar should remain sticky at the top of the viewport when it is visible.

## Screenshots

![image](https://github.com/user-attachments/assets/67c56ff7-7912-4b07-b66d-8cdc76316fe2)

## Additional Context

This functionality is commonly seen in modern web applications and can significantly improve usability.

**Comment by anamelahi** [comment]
Kindly assign me this issue

**Comment by yashmandi** [comment]
thankyou for raising this issue @anamelahi , but i have kept it in that way and have no intention of making a sticky navbar. instead there's a similar issue #59 , tell me if you can work on it, i'll assign it to you ;)
