### ISSUE TITLE
BUG : Toggle dark mode not working

### ISSUE THREAD

**Issue by shubham-mehta-002** [Scribbie-Notes/notes-app#54]
Under profile & settings:
On toggling dark mode , there is no change in the UI

**Comment by theashikagupta** [comment]
Assigned to @shubham-mehta-002 !

**Comment by A-4-Atom** [comment]
Hi, can you assign this issue to me, I'll try fixing it. @theashikagupta

**Comment by PraveenUppar** [comment]
I will work on the issue #54 assign the work to me @theashikagupta

**Comment by shubham-mehta-002** [comment]
@theashikagupta 
Already raised a PR for this issue after resolving conflicts

**Comment by PraveenUppar** [comment]
The issue was reopened again by @theashikagupta 2 hours ago

**Comment by theashikagupta** [comment]
@shubham-mehta-002 How much time it will take ?

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
