### ISSUE TITLE
Documentation Improvement: Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by aswathcm29** [Scribbie-Notes/notes-app#58]
## Description
This issue is to improve the repository's documentation by adding two essential files:

CONTRIBUTING.md: A file that outlines how contributors can effectively participate in the project.
CODE_OF_CONDUCT.md: A file that sets guidelines for community behavior to foster a welcoming environment for all contributors.

## Steps to Reproduce
Go to the repository's root directory.
Check the current documentation.
Notice the absence of CONTRIBUTING.md and CODE_OF_CONDUCT.md files.

## Expected Behavior
The repository should have both CONTRIBUTING.md and CODE_OF_CONDUCT.md files to guide potential contributors and set expectations for behavior.

## Actual Behavior
Currently, these files are missing from the repository, which might confuse new contributors or result in inconsistent behavior in the community.

**Comment by theashikagupta** [comment]
Thanks for raising this issue. Assigned to @aswathcm29!

**Comment by aswathcm29** [comment]
Done @theashikagupta ! I'll proceed with it
