### ISSUE TITLE
audio  to text converter

### ISSUE THREAD

**Issue by umesh-chilukuri** [Scribbie-Notes/notes-app#6]
why dont we add an option which enables the users not only type the content  but also using audio we can make the notes
please assign me with this task

**Comment by yashmandi** [comment]
kindly explain the technologies you're gonna use to implement this

**Comment by prateek2102** [comment]
Hi @yashmandi  , we can use Web Speech API for this, we can have a button as start recording which when clicked by user will start recording user data and button will change into stop recording and when user is done, he/she will click on stop recording and we will save the transcript as a note.
-- For saving it we can have a useState hook as string which will eventually store the text and we can save it in db as we save normal notes. 
-- we can transcribe the user's audio into text real-time or when user stops recording.

I would like to work on this feature, please assign it to me.
Or you can assign to umesh, this approach will work.

**Comment by umesh-chilukuri** [comment]
Yeah I also thought in the same way  but I was not that expert in backend so I doubt whether I can do this in efficient way

**Comment by prateek2102** [comment]
no need to worry about the backend! The backend won’t need any significant changes since we’ll be treating the transcribed text just like a regular note. We’ll send the transcribed text to the same API endpoint we’re using for saving normal notes, so the database logic remains the same. If you’re unfamiliar with setting up API routes in Express or need any help, feel free to reach out. I can assist with setting up or modifying the routes to handle this smoothly. Let me know if that works!

**Comment by umesh-chilukuri** [comment]
Then I will definitely try to do it

**Comment by yashmandi** [comment]
hi @prateek2102 , i got your approach, that's good. but i'm assigning @umesh-chilukuri for this task, we'll see how he works on it, if it does'nt meet the requirements, i will assign this task to you ;)

@umesh-chilukuri you can work on this

**Comment by umesh-chilukuri** [comment]
Thanks for the opportunity

**Comment by prateek2102** [comment]
> hi @prateek2102 , i got your approach, that's good. but i'm assigning @umesh-chilukuri for this task, we'll see how he works on it, if it does'nt meet the requirements, i will assign this task to you ;)
> 
> @umesh-chilukuri you can work on this

Perfect. Best of luck Umesh

**Comment by umesh-chilukuri** [comment]
thanks man just now completed the task and also learn some new concepts

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by prateek2102** [comment]
@theashikagupta i hope it is completed? else u can assign it to me

**Comment by theashikagupta** [comment]
@umesh-chilukuri I closed your PR bcz of merge conflicts raise a new pr with screen recording by tomorrow .

**Comment by yashmandi** [comment]
u can work on this @prateek2102

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
