### ISSUE TITLE
[BUG] Tag Management Behavior

### ISSUE THREAD

**Issue by shubham-mehta-002** [Scribbie-Notes/notes-app#63]
**Description:** 
When a user enters the same tag multiple times (e.g., "A1, A1, A1") and attempts to remove only the third instance, the current behavior results in all instances of that tag being removed. 

**Considerations:**

1. Should users be allowed to enter duplicate tags?
->If no:
Implement a validation condition to prevent the entry of duplicate tags.
->If yes:
Update the removal logic to ensure that only the specified tag is removed, rather than all of them.

**Comment by yashmandi** [comment]
no the user should not be able to enter duplicate tags. thanks for raising this issue. 
you can work on it @shubham-mehta-002

**Comment by theashikagupta** [comment]
How much time it will take ? @shubham-mehta-002
