### ISSUE TITLE
[FEAT] : Add Searchbar in header.

### ISSUE THREAD

**Issue by PriyanshuValiya** [Scribbie-Notes/notes-app#67]
# Issue Template

## Description

We should add search bar in header, so that user can find their note easily with search note title.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

I am expecting that user can search their note from the search bar, so they can easily get access to their notes.

## Actual Behavior

Describe what actually happens when you follow the steps.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Additional Context

Add any other context or information about the issue here.

**Comment by yashmandi** [comment]
hi @PriyanshuValiya 
thank you for raising the issue. but there's already a search bar in the navbar to search notes easily. 
closing this issue as no need
