### ISSUE TITLE
[BUG] Search functionality not working properly 

### ISSUE THREAD

**Issue by shubham-mehta-002** [Scribbie-Notes/notes-app#69]
**Description**
The notes should be fetched from the backend based on the user's search input. However, when the user input is empty (i.e., " "), the application should fetch and display all available notes. Currently, this functionality is not implemented.

**Steps to Reproduce**

1. Go to the notes section of the application.
2. Enter " " in the search input .
3. Press the search button.
4. Observe that "No notes found" message is displayed.

**Expected Behavior**
When the search input is empty, the application should fetch and display all notes from the backend.

**Actual Behavior**
Currently, when the search input is empty, no notes are fetched .

**Screenshot**
![image](https://github.com/user-attachments/assets/94cb5663-c967-4fa3-82cf-c002c85e6f0f)

**Comment by himughanakash** [comment]
hey @theashikagupta  @yashmandi  , could you please assign this to me?

**Comment by ishanguptaofficial** [comment]
Hello Scribbie-Notes Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by yashmandi** [comment]
thanks for your feedback @shubham-mehta-002 ! i want to clarify that the websiteis currently designed to treat an empty input as a request for no results, but i’ll pass your suggestion along for future updates ;)
