### ISSUE TITLE
Issue: Element Not Centered on Screen in Note-Taking Section

### ISSUE THREAD

**Issue by PraveenUppar** [Scribbie-Notes/notes-app#78]
# Issue Template

## Description
The element (icon and text) that instructs users to add notes is not centered on the screen.

## Steps to Reproduce

1. Go to the main page of the web app after login.
2. Observe the note-taking icon and message on the screen.
3. Notice that the element is not vertically and/or horizontally centered.

## Expected Behavior

The note-taking icon and message should be perfectly centered both horizontally and vertically on the screen.

## Actual Behavior

The note-taking icon and message are aligned towards one side, not in the center of the screen as expected.
## Screenshots
![Screenshot 2024-10-03 220245](https://github.com/user-attachments/assets/88ce3b43-9264-4fb9-91fe-cae78eca73f7)

**Comment by theashikagupta** [comment]
![Screenshot 2024-10-03 234456](https://github.com/user-attachments/assets/2ece2668-6a3a-49a7-b8da-82cbd9dabc29)
Issue does not exist
