### ISSUE TITLE
Profile pic upload issue

### ISSUE THREAD

**Issue by saurabh-dev-vns** [Scribbie-Notes/notes-app#8]
I have seen your project, which is awesome, but you are facing an issue where you are unable to upload a profile picture because you are using Vercel for hosting. Vercel does not provide storage features, so you will need another service, such as AWS S3, Cloudinary, etc., to store the uploaded media files.

I am capable of resolving this issue, but first, you need to choose a platform for media file storage.

**Comment by yashmandi** [comment]
thank you for raising the issue, Saurabh.
but currently i dont have any plans for hosting this project on cloud services like AWS, maybe i will reach out to you in the future about this issue ;)
