### ISSUE TITLE
feat: Display All Pinned Notes Separately on Notes Page

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#84]
# Issue Template

### Description
Currently, pinned notes are either displayed mixed with regular notes or not highlighted separately. This makes it difficult to distinguish important notes from others. To improve note organization and prioritization, I propose displaying pinned notes in a dedicated section or displaying them separately on the notes page.

### Acceptance Criteria:

- Pinned notes should be displayed in a separate section above regular notes.
- The layout should clearly differentiate pinned notes from unpinned notes, e.g., through styling or visual separation.
- The section for pinned notes should remain empty if no notes are pinned.
- Ensure responsiveness and proper alignment across different screen sizes.
- Allow the user to unpin notes, which should move them back to the regular notes section.

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta @yashmandi ,  can you assign this to me

**Comment by theashikagupta** [comment]
Assigned ! @Saurabhchaudhary9799
