### ISSUE TITLE
feat : Add Background Color to Notes

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Scribbie-Notes/notes-app#87]
### Description : 
 Enable users to select and apply different background colors to their notes for better organization and personalization.

### Feature Details : 

-   Add a color picker option when creating or editing a note.
- The selected background color should be saved and displayed on the note in both the list and detail views.
- Ensure the feature is responsive and visually consistent with the app's design.
- Optionally, allow users to reset the background color to default.

### Acceptance Criteria:

1. Users can pick from a predefined set of background colors or customize their own.
2. The selected color is saved with the note and displayed correctly across sessions.
3. The UI should remain user-friendly and intuitive.

**Comment by Saurabhchaudhary9799** [comment]
hey @theashikagupta @yashmandi , could you please assign this to me?

**Comment by theashikagupta** [comment]
Assigned! @Saurabhchaudhary9799

**Comment by DhruvGahoi** [comment]
@theashikagupta I'm facing issue while connecting with my MONGODB_URI, can you help me with that, so I could start working on other issues?

![image](https://github.com/user-attachments/assets/6f891063-5063-41e6-a670-e0486e58512b)

**Comment by DhruvGahoi** [comment]
@yashmandi can you help me with that please ?

**Comment by OINDIL** [comment]
I guess the issue is with the .env variable, create .env in the backend as well as in the front end folder and add the mongodb connection string to it!

**Comment by DhruvGahoi** [comment]
@OINDIL I have did everything as stated in README
still itss showing this error

**Comment by OINDIL** [comment]
Did you try the new readme or the old one?

**Comment by DhruvGahoi** [comment]
the new one

**Comment by Saurabhchaudhary9799** [comment]
![backendEnv](https://github.com/user-attachments/assets/c8115771-63f6-4302-a250-5d791832c000)
hey @theashikagupta , is your .env file format like this env in photo

**Comment by DhruvGahoi** [comment]
@Saurabhchaudhary9799 
![image](https://github.com/user-attachments/assets/ab10d93f-9bbe-4917-86c3-feffced2630b)
Something like this
