### ISSUE TITLE
No field validations during signup 

### ISSUE THREAD

**Issue by shubham-mehta-002** [Scribbie-Notes/notes-app#9]
During the signup process, there should be a proper field validation
like the name should not contain any special characters or numbers.
Similarily other fields should have proper validation like email, password, etc.

**Comment by shubham-mehta-002** [comment]
@yashmandi 
I can resolve this issue 

Also added gssoc / hacktober labels to this issue

**Comment by shubham-mehta-002** [comment]
Hi, I've made a pull request
Kindly check !!

**Comment by ADeshmukh80** [comment]
Please assign this task to me
