### ISSUE TITLE
[BUG] Misalignment of email and phone in user account page

### ISSUE THREAD

**Issue by Vaishh18** [Scribbie-Notes/notes-app#92]
## Description
The "Change Email" and "Change Phone" options under "My Account" on Scribbie's website are not aligned properly.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'scribbie's website'
2. Click on 'Login'
3. Go to 'Profile & Settings and under My Account'  
4. Observe the misalignment of the "Change Email" and "Change Phone" options.

## Expected Behavior

The "Change Email" and "Change Phone" options should be properly aligned under the "My Account" section, maintaining a consistent layout.

## Actual Behavior

The "Change Email" and "Change Phone" options are misaligned under "My Account," leading to a visually inconsistent layout.

## Screenshots
![Screenshot (1052)](https://github.com/user-attachments/assets/bcc0794c-af51-4890-a0a5-11677244d582)
![Screenshot (1051)](https://github.com/user-attachments/assets/4f772d87-0bb0-4b7b-a5bb-3d3bb105f27e)

**Comment by Vaishh18** [comment]
hey @theashikagupta @yashmandi , could you please assign this to me?

**Comment by yashmandi** [comment]
you can work on it @Vaishh18

**Comment by theashikagupta** [comment]
@Vaishh18 How much time it will take ?

**Comment by Vaishh18** [comment]
@theashikagupta will make pr today only
