### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by devarsheecodess** [Scribbie-Notes/notes-app#96]
# Issue Template

## Description

The footer is too huge and looks very basic and also lacks social icons (like instagram, X, github, etc)

## Screenshots

![image](https://github.com/user-attachments/assets/516a74ae-b4ee-4c41-8763-664e4bbb4eda)

I want to fix this issue. @yashmandi , plz assign ,me this task under gssoc-extd label

**Comment by yashmandi** [comment]
explain what are you gonna enhance in detail

**Comment by devarsheecodess** [comment]
> explain what are you gonna enhance in detail
> 

The footer is too big, so I will reduce its size by moving "Scribble" at bottom left and rest of the options at bottom right. also we can add social icons like instagram, GitHub, twitter, etc. And ig there is no scroll to top button so I can also add that button

**Comment by yashmandi** [comment]
ok u can work on it @devarsheecodess 
just dont work on scroll-to-top button as someone is working on it, u can work on other features u mentioned
