### ISSUE TITLE
Fix: Backend folder's index.js file's Routers needs to be streamlined

### ISSUE THREAD

**Issue by OINDIL** [Scribbie-Notes/notes-app#97]
# Issue Template

## Description
The Backend has a lot of routes in the index.js file. I wanted to streamline the file by using express router.

## Steps to Reproduce

Please provide step-by-step instructions on how to reproduce the issue:

1. Go to 'index.js'
2. Scroll down to 'line 46'
4. See there are a lot of routes that are making the index.js file complicated to understand.

## Expected Behavior

I want to streamline the index.js file by adding Express Router and a Specific Router folder.

## Actual Behavior
If I add the router folder then it will be straightforward to understand.

## Screenshots
![image](https://github.com/user-attachments/assets/d16f2da0-7f42-4cb0-877f-40738ed2dce5)

@yashmandi, I would love to work on this issue.

**Comment by yashmandi** [comment]
could u please explain more in detail @OINDIL

**Comment by OINDIL** [comment]
The index.js file is overpopulated with all the routes inside it.  See from the line 46 and till the end of the file. I want to separate the routes in a different file so that the main server file which is index.js can be simplified.

**Comment by OINDIL** [comment]
@yashmandi node_modules folder is getting uploaded again.

**Comment by OINDIL** [comment]
@yashmandi the routes have been added. But when I tested the old code before my changes the login route was not working, and I didn't change the code. But I have added my issue changes, and the login route is still not working. A user model was missing from the old script, so I fixed that too.
![image](https://github.com/user-attachments/assets/45b0f218-baeb-4c7d-865d-f84b2a57131a)

**Comment by yashmandi** [comment]
yes the login route has some issues, no worrier i'll merge it
