### ISSUE TITLE
bug: Misalignment of "Sign in with Google" Button and Login Button

### ISSUE THREAD

**Issue by userAdityaa** [Scribbie-Notes/notes-app#99]
# Issue Template

## Description
The "Sign in with Google" button and the login button do not seem to be visually aligned properly on the horizontal axis, leading to an inconsistent user interface. 

## Steps to Reproduce
- Press the login button in the home page navbar. 
- Then, Coming to the login page, Observe the "Sign in with Google" button and the login button.

## Expected Behavior

- Both the "Sign in with Google" button and the login button should be horizontally aligned for a cleaner and more cohesive appearance.
## Actual Behavior
- The button and button appear visually misaligned, disrupting the flow of the login interface

## Screenshots
<img width="322" alt="Screenshot 2024-10-05 at 12 02 04 AM" src="https://github.com/user-attachments/assets/1250c810-438c-4140-9d15-03503c123b45">

## Additional Context

The Google sign in feels more towards up than the login button.

**Comment by userAdityaa** [comment]
@yashmandi, Assign this to me.

**Comment by yashmandi** [comment]
thanks for raising an issue, but currently it is not required ;)
